### ISSUE TITLE
Add support for MCPO's

### ISSUE THREAD

**Issue by jasonpan12** [box/boxcli#100]
Feature request: Add support for metadata cascade policies!

**Comment by mattwiller** [comment]
Hi @jasonpan12 — we're currently in the process of a major update of the CLI, and adding support for all currently-unsupported API endpoints will happen as a part of that effort.  We'll keep you updated when the new version is released!

**Comment by mattwiller** [comment]
The latest v2.0.0 release of the CLI includes support for Metadata Cascade Policies; please let us know if there's any other missing functionality in the latest version!
