### ISSUE TITLE
Add support for generic request

### ISSUE THREAD

**Issue by jtrujillo3** [box/boxcli#101]
Support for generic requests like the SDKs have for cases where the CLI does not yet have a command for. i.e. metadata cascade policies

**Comment by mattwiller** [comment]
@jtrujillo3 Thanks for the feature idea!  I think this is a good candidate for inclusion in the SDK.  We're currently in the process of a major update of the CLI, so this will probably happen as a part of that effort.

**Comment by dann815** [comment]
+1

**Comment by mattwiller** [comment]
This functionality was added in the v2.0.0 release under the `box request` command.  The latest installers are available over at https://github.com/box/boxcli/releases/tag/v2.0.0 — please give it a try and let us know if there's anything else you would like added to this feature!
