### ISSUE TITLE
Large Files (4gb) consistently fail to upload with "The format of value 'bytes XXX-YYY/ZZZ' is invalid". error

### ISSUE THREAD

**Issue by mbehn** [box/boxcli#102]
When attempting to upload a 4GB file through the CLI, the process consistently stops at 100% then throws the below error.

`mba-007695:Desktop mbehn$ box files upload -p 0 testfile.tmp 
File name: testfile.tmp
Processing testfile.tmp
Processing... [====================================================================================================] 100%The format of value 'bytes 4294967296-4294967295/4294967296' is invalid.
mba-007695:Desktop mbehn$ `

It seems there might be an issue with how the CLI handles the final commit when uploading a file of this size.

**Comment by mattwiller** [comment]
@mbehn Thanks for letting us know!  It looks like the CLI currently uses its own custom implementation of the Chunked Upload flow.  The error appears to be actually happening before the commit, in the upload of the last part — it essentially tries to say it's uploading bytes N through N-1, which doesn't really make sense.  We're currently in the middle of a major update to the CLI which should resolve this issue; I'll validate that it does and this should get fixed when the new version is released.

**Comment by jmfrank63** [comment]
I got a patch for this an it works with up to 15GB. Should I sent a pull request?

**Comment by mattwiller** [comment]
This issue should be resolved in v2.0.0, so I'm going to close this out.  Please let us know if you come across any issues in the new version!
