### ISSUE TITLE
Add notify boolean to collaboration commands

### ISSUE THREAD

**Issue by jtrujillo3** [box/boxcli#105]
The create collaboration endpoint has the option to suppress email notifications but the CLI add collaboration command does not.  

Common use cases for the CLI are to set up a new users environment prior to them logging in and the email notifications can be confusing.

**Comment by mattwiller** [comment]
@jtrujillo3 We're currently working on a new version of the CLI where this issue is already resolved; in order to focus our efforts we'll plan to defer resolution of this issue until that version is released.  We'll update this ticket as progress is made on that front!

**Comment by mattwiller** [comment]
The `box collaborations:add`, `box folders:collaborations:add`, and `box files:collaborations:add` commands should all now (as of v2.0.0) support a `--no-notify` flag to suppress notifications.  Please let us know if you run into any other issues with the CLI!
