### ISSUE TITLE
FEATURE REQUEST: Better documentation for bulk operations

### ISSUE THREAD

**Issue by grugknuckle** [box/boxcli#108]
When performing bulk operations from a .csv or .json file, it is not at all clear what fields are required or how they should be named. Better documentation is needed *somewhere* - it doesn't have to be from the cli's native --help flag.

For example: 
I have a .json file like the (BAD) one below. When I run the CLI command

`
box files upload --bulk-file-path "{filePath}" --as-user {userID}
`

I get the error

`
Object reference not set to an instance of an object.
`

for each file item I'm attempting to upload. However, if I change the key to "path" from "filePath" it works. THE PROBLEM: I had to *guess* what the field keys were supposed to be and they didn't match the field names I found in the CLI --help section.

PLEASE FIX YOUR DOCUMENTATION

BAD .json File
```
[
  {
    "filePath": "O:\\Apps\\e_app_file\\2018\\183141\\From Customer\\BETE.pdf",
    "parent": {
      "id": "56042357153"
    },
    "name": "BETE.pdf"
  },
  ...
]
```

GOOD .json File
```
[
  {
    "path": "O:\\Apps\\e_app_file\\2018\\183141\\From Customer\\BETE.pdf",
    "parent": {
      "id": "56042357153"
    },
    "name": "BETE.pdf"
  },
  ...
]
```

**Comment by mattwiller** [comment]
@grugknuckle Sorry about that — this feature is currently a bit difficult to use.  We're working on v2.0.0 of the CLI now (scheduled for release in December) — that version will align the field names in the JSON and CSV bulk input file formats with the argument and flag names in the command help, which should resolve this problem.

**Comment by grugknuckle** [comment]
Thank you @mattwiller for responding to this. I am happy to hear that your team is working to improve this tool. In the short run, where can I ask for help with the current version of the CLI? The Box community forums are not very helpful at all.

**Comment by mattwiller** [comment]
Here in GitHub issues is the best place, since my team monitors these directly and can help investigate any issues you have.

**Comment by mattwiller** [comment]
@grugknuckle The latest version of the CLI (v2.0.0) includes a completely reworked bulk input system that matches input properties with the command-line flags and arguments that you can view by running any command with `--help`.  This should hopefully make bulk input much more intuitive!  Please download the latest version over at https://github.com/box/boxcli/releases/tag/v2.0.0 and give it a try — we'd love to hear any feedback on the new version you might have!

**Comment by grugknuckle** [comment]
@mattwiller Thank you for this and for your prompt responses. This is a big improvement.
