### ISSUE TITLE
Add Support to get more than 30 files containing specific naming scheme or ext

### ISSUE THREAD

**Issue by abarber229** [box/boxcli#109]
Looks like currently Box CLI only can return 30 files at once. Is there a way for it to return like hundreds of files through the CLI?

**Comment by mattwiller** [comment]
@abarber229 What command are you running?  If it's `box search`, there is not a way currently to get more results.  We're working on this issue in the upcoming v2 release of the CLI, and will at the very least probably increase the default number of results returned to around 100.

**Comment by mattwiller** [comment]
In the current version of the CLI, there is no way to get more than the initial set of search results, but the next version of the CLI will be released by December 13th.

**Comment by abarber229** [comment]
Thank you!

**Comment by abarber229** [comment]
Did the new boxcli get released today?

Thank you.

**Comment by mattwiller** [comment]
@abarber229 It was released today!  You can find the new installers at https://github.com/box/boxcli/releases/tag/v2.0.0 — please give it a try and let us know if you run into any issues!

**Comment by abarber229** [comment]
So I updated to the newest version. However, the search parameters are returning incorrect results unless I am using the search command incorrectly. Here is the command that I am running - box search "SORRY-FOR-FILES" --fields="id" --fields="name" --file-extensions="html" --token "inserttokenhere" > "C:\Temp\Sorry-For-Files.csv". The Sorry-For-Files search field is not returning any files that say that. Thoughts?

Here are a couple of examples:

[
    {
        "type": "file",
        "id": "363197203723",
        "name": "glossary.html"
    },
    {
        "type": "file",
        "id": "363196393723",
        "name": "glossary.html"
    },
    {
        "type": "file",
        "id": "363196717723",
        "name": "glossary.html"
    },
    {
        "type": "file",
        "id": "363188206281",
        "name": "MPO - RMPO-W1190-811.html"

**Comment by abarber229** [comment]
sorry for getting back to you late. I used to be able to just run "box search "Sorry-for-files" --token "token"" and export that to a file in V1. I tried it your way in the example and returned these results.  I am only getting HTML files but without the name that I am searching for. The script looks to skip the query file name that I would like to find. The return were the same results I posted before. Examples are below again. Any other idea or commands? Could you create an "Sorry-For-Files.html" in your environment to test?

type,id,name
file,370619319764,viewer.html
file,370649219066,viewer.html
file,369924997556,viewer.html
file,369928631504,viewer.html
file,363197203723,glossary.html
file,363196393723,glossary.html
file,363196717723,glossary.html

**Comment by abarber229** [comment]
here is the verbose output if that helps:

```
C:\Program Files\@boxcli>box search '"SORRY-FOR-FILES"' --fields name --file-extensions html --token "mytoken" -v
  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'search', '\'SORRY-FOR-FILES\'', '--fields', 'name', '--file-extensions', 'html', '--token', 'mytoken', '-v' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings { boxReportsFolderPath: 'C:\\Users\\barbera\\Documents\\Box-Reports',
  box-cli:init   boxReportsFolderName: 'Box-Reports',
  box-cli:init   boxReportsFileFormat: 'json',
  box-cli:init   boxDownloadsFolderPath: 'C:\\Users\\barbera\\Downloads\\Box-Downloads',
  box-cli:init   boxDownloadsFolderName: 'Box-Downloads',
  box-cli:init   autoSave: false,
  box-cli:init   outputJson: true } +2ms
  box-cli:init Using passed in token mytoken+1ms
  box-cli:execute Starting execution command: search argv: [ '\'SORRY-FOR-FILES\'',
  box-cli:execute   '--fields',
  box-cli:execute   'name',
  box-cli:execute   '--file-extensions',
  box-cli:execute   'html',
  box-cli:execute   '--token',
  box-cli:execute   'mytoken',
  box-cli:execute   '-v' ] +0ms
```

**Comment by mattwiller** [comment]
@abarber229 I'm able to make this work correctly on my machine (a Macbook), but the verbose output you gave is very helpful — the issue seems to be with how your Windows shell is passing the quoted string to the CLI.  Here's the key difference:

What the CLI sees on my machine:
```
  box-cli:execute Starting execution command: search argv: [ '"SORRY-FOR-FILES"',
  box-cli:execute   '--fields',
  box-cli:execute   'name',
  box-cli:execute   '--file-extensions',
  box-cli:execute   'html',
  box-cli:execute   '--token',
  box-cli:execute   'mytoken',
  box-cli:execute   '-v' ] +0ms
```

What the CLI sees on your machine:
```
  box-cli:execute Starting execution command: search argv: [ '\'SORRY-FOR-FILES\'',
  box-cli:execute   '--fields',
  box-cli:execute   'name',
  box-cli:execute   '--file-extensions',
  box-cli:execute   'html',
  box-cli:execute   '--token',
  box-cli:execute   'mytoken',
  box-cli:execute   '-v' ] +0ms
```

I'm not totally sure why, but your shell is passing single quotes to the CLI instead of double quotes — the Search API requires double quotes for specifying an exact match.  Could you try just escaping the double quotes instead, like this:
```
box search \"SORRY-FOR-FILES\" --fields name --file-extensions html
```

Please let me know if that does the trick!

**Comment by abarber229** [comment]
Looks to be pulling zero results now. However, the search looks to be correct like you mentioned. I can confirm that their are filenames that match the criteria. 

```
C:\Program Files\@boxcli>box search \"SORRY-FOR-FILES\" --fields name --file-extensions html --token "L4IxZOtrnQhxfvMA4Q0bzEtqbGdzNUyI" -v
  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'search', '"SORRY-FOR-FILES"', '--fields', 'name', '--file-extensions', 'html', '--token', 'token', '-v' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings { boxReportsFolderPath: 'C:\\Users\\barbera\\Documents\\Box-Reports',
  box-cli:init   boxReportsFolderName: 'Box-Reports',
  box-cli:init   boxReportsFileFormat: 'json',
  box-cli:init   boxDownloadsFolderPath: 'C:\\Users\\barbera\\Downloads\\Box-Downloads',
  box-cli:init   boxDownloadsFolderName: 'Box-Downloads',
  box-cli:init   autoSave: false,
  box-cli:init   outputJson: true } +1ms
  box-cli:init Using passed in token token +1ms
  box-cli:execute Starting execution command: search argv: [ '"SORRY-FOR-FILES"',
  box-cli:execute   '--fields',
  box-cli:execute   'name',
  box-cli:execute   '--file-extensions',
  box-cli:execute   'html',
  box-cli:execute   '--token',
  box-cli:execute   'tokten',
  box-cli:execute   '-v' ] +0ms
  box-cli:output Formatted 0 output entries for display +0ms
  box-cli:output Using json output format +0ms
  box-cli:output Processed output as JSON +2ms
  box-cli:output Writing output to terminal +1ms
[]
  box-cli:output Finished writing output +4m
```s

**Comment by mattwiller** [comment]
@abarber229 Now the `argv` is identical to what I'm seeing on my machine (where I get the correct results), I would suspect that the CLI is making the correct API call on your machine.  In that case, the issue might be with your specific environment.  Here are a few other things to check:

- Ensure that the token you're using is for an account with access to the files you want to find — you can run `box users:get me --token <TOKEN>` to check which account you're making calls as with that token.  If you know the file ID of the file you're trying to find, you can also run `box files:get <FILE_ID> --token <TOKEN>` to verify that the account has access to the file in question.
- If the file was recently uploaded, it may not have been indexed for search yet.  New files can take ~10 minutes to be indexed.
- The double quotes make the search query require an exact match.  You should check that the filename or content you're looking for matches character for character.

**Comment by mattwiller** [comment]
@abarber229 Well, at least that tells us that the issue probably isn't in the search command!  The first thing to check here would be the token you're passing in — how are you getting it?  Also, when you run `box users:get me --fields login --token <THAT_TOKEN>`, do you see the same email address you use to log into the web application?

**Comment by abarber229** [comment]
I'm getting the token from the Box Dev Console. When I run the get me command, it does return the same email address that I am using to login to Box.com with. Would you like to share screens today?

C:\Program Files\@boxcli>box users:get me --token "token" -v
  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'users:get', 'me', '--token', 'token', '-v' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings { boxReportsFolderPath: 'C:\\Users\\barbera\\Documents\\Box-Reports',
  box-cli:init   boxReportsFolderName: 'Box-Reports',
  box-cli:init   boxReportsFileFormat: 'json',
  box-cli:init   boxDownloadsFolderPath: 'C:\\Users\\barbera\\Downloads\\Box-Downloads',
  box-cli:init   boxDownloadsFolderName: 'Box-Downloads',
  box-cli:init   autoSave: false,
  box-cli:init   outputJson: true } +2ms
  box-cli:init Using passed in token token+2ms
  box-cli:execute Starting execution command: users:get argv: [ 'me', '--token', 'token', '-v' ] +0ms
  box-cli:output Formatted output content for display +0ms
  box-cli:output Using json output format +1ms
  box-cli:output Processed output as JSON +1ms
  box-cli:output Writing output to terminal +0ms
{
    "type": "user",
    "id": "213243789",
    "name": "austin barber",
    "login": "barbera@bakerconcrete.com",
    "created_at": "2014-03-14T07:42:09-07:00",
    "modified_at": "2018-12-27T06:45:01-08:00",
    "language": "en",
    "timezone": "America/New_York",
    "space_amount": 1000000000000000,
    "space_used": 459702483450,
    "max_upload_size": 16106127360,
    "status": "active",
    "job_title": "",
    "phone": "",
    "address": "",
    "avatar_url": "https://bakerconcrete.app.box.com/api/avatar/large/213243789"
}
  box-cli:output Finished writing output +1ms

**Comment by mattwiller** [comment]
@abarber229 Given the behavior you're describing, it seems like the issue here isn't with the CLI — everything appears to be working as expected there.  For additional troubleshooting, you should open a ticket with [Box Support](https://support.box.com) — they can help you diagnose the issue further!
