### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by kazunoriobata** [box/boxcli#115]
For windows, v1 seems to use OS proxy setting by default. However v2 does not seem to use proxy setting. Is it possible to fix? Otherwise please tell me how should we do.

**Comment by mattwiller** [comment]
@kazunoriobata We'll probably need to add some configuration options to allow setting the proxy information.  To help us implement this functionality, what sort of proxy settings are you using?  That way we can ensure that they would be supported by the CLI.

**Comment by mattwiller** [comment]
@kazunoriobata Great — thank you for the information!  Is there a specific type of proxy authentication that you would need to be supported?

**Comment by kazunoriobata** [comment]
@mattwiller I think it's basic authentication.

**Comment by boxcli** [comment]
will you support proxy?

**Comment by mattwiller** [comment]
@boxcli Proxy support is a feature that we are planning to add eventually, but it is not currently on our immediate roadmap.

**Comment by boxcli** [comment]
Any idea which version will eventually include proxy support?

**Comment by boxcli** [comment]
Hi, is there any workaround to make BoxCLI work behind corporate proxy?
