### ISSUE TITLE
Request: Option to return the ID/object of the existing folder instead of an error in create:folder if the folder exists

### ISSUE THREAD

**Issue by TimFikes** [box/boxcli#116]
I have processes that need to create a folder, or use the folder if it exists.   

The error in 1.4.0 was provided in JSON format, and contained the ID, so I was able to extract the ID from the error.  This wasn't ideal, but it worked.

However, in 2.0.0 the error response is very terse: "Unexpected API Response [409 Conflict | ...] item_name_in_use - Item with the same name already exists"  I am thinking I will have to now convert my code to a two-step process: issue a search command, issue a create:folder command.  

Is there a straightforward way to do this in a single step?  Maybe there is and I just haven't seen it.

A useful feature would be the option to get the same response back from folder:create for the existing folder that you get for a new folder.  Something like --return-existing-folder

Thanks for any help you can provide!

**Comment by mattwiller** [comment]
@TimFikes Thanks for letting us know!  We'll look into how we could expand the error format to include the extra information in these sorts of responses, or enable these operations to be more idempotent.
