### ISSUE TITLE
Request : list collaboration whitelist

### ISSUE THREAD

**Issue by kazunoriobata** [box/boxcli#117]
I would like you to add an option to export a list of all collaboration whitelist.

**Comment by mattwiller** [comment]
@kazunoriobata This functionality is available in v2.0.0 of the CLI, under the `box collaboration-whitelist` command.  Could you try that out and let me know if it works for your use case?

**Comment by kazunoriobata** [comment]
@mattwiller I tried but it is necessary to specify ID of an entry. Is it possible to get all the entries at once?

**Comment by kazunoriobata** [comment]
@mattwiller Oh. Thank you. I didn't think it could be done without any sub commands.
