### ISSUE TITLE
Added aliases are requiring confirmation

### ISSUE THREAD

**Issue by jasonpan12** [box/boxcli#119]
Hello!

I'm running into an issue where email aliases added through the CLI are still requiring confirmation. For example:
```
`$ box users:email-aliases:add 609497292 jpan+3423252@deucedeuce.co
Type: email_alias
ID: '17896106'
Is Confirmed: false
Email: jpan+3423252@deucedeuce.co`
```

However, I can take a token from the same CLI environment and pass it into Postman, and the created alias will be already confirmed
![screen shot 2019-01-03 at 1 40 33 pm](https://user-images.githubusercontent.com/18650238/50663597-c3aa1180-0f6f-11e9-950a-19b924b259f0.png)

From inspecting the CLI request via fiddler, there aren't any special parameters being passed vs the postman call. Both the CLI and Postman aren't passing query parameters, and the only body parameter is
`{"email":"jpan+555552@deucedeuce.co"}`

I can't figure out what's different about the CLI request vs the Postman request... this call also used to work in CLI v1.

**Comment by mattwiller** [comment]
@jasonpan12 If the two versions of the CLI are making identical calls, I'm guessing the issue is in the API or with the specific account that's making the call.  If you run `box users get me` in the v1 CLI and `box users:get me` in the v2 CLI, do you get the same user?

**Comment by jtrujillo3** [comment]
working with a customer on trying to bulk add email aliases vis the CLI and running into same behavior.

  In the Box Java SDK i see that you have to pass another parameter to confirm the email when adding it https://github.com/box/box-java-sdk/blob/master/doc/users.md#add-email-alias Wondering if the change to v2 made the CLI behave similar to that?

**Comment by mattwiller** [comment]
@jtrujillo3 @jasonpan12 Ah, I figured out what's happening.  The v1 CLI [does not explicitly pass a parameter](https://github.com/box/boxcli/blob/v1/BoxCLI/Commands/UserSubCommands/UserAddEmailAliasCommand.cs#L51) around the alias being confirmed.  The [AddEmailAliasAsync() method](https://github.com/box/box-windows-sdk-v2/blob/fc44cb8caded602577c21bc93b8b5d64b51fb392/Box.V2/Managers/BoxUsersManager.cs#L256) it calls in the .NET SDK also does not reference the `is_confirmed` parameter, and just populates a [small request model](https://github.com/box/box-windows-sdk-v2/blob/5800ee9aa621493d6d23d8628b2bf5b20057309a/Box.V2/Models/Request/BoxEmailAliasRequest.cs) that also doesn't reference the parameter.  So, there was never any explicit parameter being passed.

However, it looks like the API is set up to __automatically confirm email aliases made by admins unless they explicitly set `is_confirmed` to `false`__, and for historical reasons [the Node.js SDK that the v2 CLI uses sends `is_confirmed: false` by default](https://github.com/box/box-node-sdk/blob/master/lib/managers/users.js#L143).

Changing either that default in the Node SDK or the current CLI behavior would be a breaking change, but we could add a `--confirm` flag to the v2 CLI command to enable confirming the email alias.  Would that work?

**Comment by jtrujillo3** [comment]
Yes that should work perfectly!  Thank you.
