### ISSUE TITLE
box events missing pagination options and stream_position parameter 

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#122]
I'm trying to create an automatic events report system for my client but it turns out Boxcli can only return 500 items max and has no pagination option.
Here's the use case, we would like to run a daily batch that runs at midnight and returns all logs from the prior day.  The`created-after` query does not return more than 500 items. I would like to iterate thru the results until it returns 0 items.

`box events -e  --created-after=created-after`

Also the result does not include the `streamposition` value. It would be great if I could get that result as a `--id-only` param and iterate thru results.

**Comment by mattwiller** [comment]
@Band-Aid Have you tried using `box events:poll` instead?  That should handle pagination for you, and has options for the start and end date on the enterprise events stream.

**Comment by Band-Aid** [comment]
@mattwiller  I just tried the command but nothing is returned to the console.
Am I doing anything wrong? 
`box events:poll -e --start-date=2019-01-01 --end-date=now`
`box events:poll -e --start-date=2019-01-01 --end-date=2019-01-01`

**Comment by isaac-galvan** [comment]
@mattwiller I can't get any output from the events:poll command either.
Any help? Does it actually work for you all at Box?

**Comment by mattwiller** [comment]
@isaac-galvan @Band-Aid  It does seem like the command is not working as intended, especially for enterprise events.  I'll investigate first thing next week and work on a fix, but I think we're probably looking at a few different things:

1. The `box events`/`box events:list` command should do more to give you the full set of event results.  This would likely require us to ensure that the results set is bounded — currently this is more or less the case, but we would probably want to formalize this a bit.  What do you think of something like this?

    * If the `--stream-position` flag is passed, we'll give back the next N events from that
      stream position (where N can be set via the `--limit` flag)
    * Otherwise, we will require time bounds.  We can default the end time to the present 
      time and the start time to some period before the end time (maybe like 5 
      days?).  In this case, we should output all events between those times

2. It seems like the `box events:poll` command isn't correctly returning events from the past — we'll start investigating there and get it fixed.

**Comment by isaac-galvan** [comment]
@mattwiller I think the second option, to provide a start and end time, would be best. This would fit our use case best, I believe.

**Comment by mattwiller** [comment]
@isaac-galvan Great!  I'll start work on this today and link this issue to the PR when it's ready.
