### ISSUE TITLE
--fields not working with groups:list command

### ISSUE THREAD

**Issue by isaac-galvan** [box/boxcli#123]
Running the command `box groups` work just fine and I get the group with some fields as expected.

However, when running `box groups:list --fields=id,name,description`, only the type,ID, and name fields are returned. I have tried this with other fields, such as `created_at` and `provenance`, and they are not returned either.

**Comment by isaac-galvan** [comment]
Looks like we can't retrieve the `provenance` field when specifying a single group either.

**Comment by mattwiller** [comment]
@isaac-galvan Thanks for the report — we're aware of the issue and have a PR open to resole it (#113).  This will be included in the next CLI release, which should be in the next week or so.
