### ISSUE TITLE
--fields=sync state not working with box folder: get 

### ISSUE THREAD

**Issue by TonyHuckle** [box/boxcli#124]
when running 'box folders:get <folder id> --as-user= <user id> --fields=sync_state'

only the type and ID fields are returned.

expected sync_state which is returned when doing the following in postman 

curl -X GET \
  'https://api.box.com/2.0/folders/<id>?fields=sync_state' \
  -H 'Authorization: Bearer <>' \
  -H 'Postman-Token: <>' \
  -H 'cache-control: no-cache'

I get the result

{
    "type": "folder",
    "id": "<>",
    "etag": "2",
    "sync_state": "synced"
}

**Comment by mattwiller** [comment]
@TonyHuckle This issue has already been resolved on master with #113 and will be fixed in the next CLI release!
