### ISSUE TITLE
Box Folder Download Overwrite/Ignore

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#125]
When you using the box folders:download option there is no option of ignore existing files or overwrite in the target.  This means that we cannot download as it fails as soon as a folder already exists.

Would it be possible to define a 'skip' or 'overwrite' when doing a folder download?

**Comment by mattwiller** [comment]
@jacquesvandermerwe Can you elaborate more on the use case for this?  If a user wants to overwrite any existing files anyway, they should be able to delete the folder they already have and re-download — that would have the same effect.  Is there a compelling case for the skip behavior?

**Comment by jacquesvandermerwe** [comment]
@mattwiller This is an action that is done for a LOT of content. The box cli is used in combination with Upload and Download actions. Only new data is synced down and the other source uploads new content which is then synced back up to Box. So the CLI is being used to create a stable state. With the amount content it will cause excessive price spikes on the platform API call count and bandwidth costs. So if the content already exists it should not be overwritten but skipped.

**Comment by mattwiller** [comment]
@jacquesvandermerwe Makes sense to me!  I'll add this to our backlog.

**Comment by mgrytsai** [comment]
This issue was closed by mistake.

There is already a corresponding [Pulse request #39125995](https://pulse.box.com/forums/909778/suggestions/39125995). We'll review this request and add to the roadmap in a few quarters.

**Comment by plmeta** [comment]
Hello, just wondering if there is any update on this topic? Thx!

**Comment by mgrytsai** [comment]
Hi @plmeta 

This change isn't planned for the next release (Aug-Nov 2023), however we'll evaluate it for the next release cycle. Team is currently busy with making significant enhancement to underlying library we use and after that we will evaluate our roadmap and consider this change.

**Comment by congminh1254** [comment]
Hi @plmeta 

We have just implemented this feature and it should be included in the next release.

**Comment by robinshi123** [comment]
Is it possible to also implement this feature to box folders:update? I encountered this issue when the uploading process got interrupted and I am not allowed to continue the process  as it fails as soon as a folder already exists.
