### ISSUE TITLE
update user missing enteprise option

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#127]
We're trying downgrade managed users to a free account but couldn't find the enterprise option.
I think this could be done using the bulk command but we'd like to be able to process line by line.

It would look something like this
`box users:update Id -e null`

I have a client that invites external collabs as a managed user while working on projects with them. Once the project ends, they release them back in to the wild.

**Comment by mattwiller** [comment]
@Band-Aid I think `box users:update [ID] --remove` should do what you want — could you give that a try and let me know if it works for you?

**Comment by Band-Aid** [comment]
Thanks! I got it to work!
