### ISSUE TITLE
Box Users External Users Empty

### ISSUE THREAD

**Issue by jaredneedell** [box/boxcli#135]
I am getting null response when trying to search for External Users.

I have 350 external users and can confirm my box cli is working since I can return all my managed users.

I am using the command box users -e which returns nothing.

**Comment by mattwiller** [comment]
@jaredneedell It looks like the underlying API endpoint does not return the list of external users.  This is almost certainly not an issue with the CLI, but rather with the API itself.  We'll follow up with the Box team that owns this API endpoint and let you know when we have any updates to share!

**Comment by mattwiller** [comment]
@jaredneedell I spoke to the Box team that owns the Users API, and this is unfortunately an issue with the way this API was originally designed.  There is currently no way to get a list of all external users from the Box API, so the CLI is unable to do what you're looking for.  I'm going to keep this issue open so we can track it, but for now I don't have an ETA to share about when this might get resolved.

**Comment by JackCulwell** [comment]
Is there any progress on this. Even if the filter on the command was extended to support wildcards, it would be better than nothing. 
.\box users -e --filter='*'

**Comment by sujaygarlanka** [comment]
@jaredneedell @JackCulwell As this is still not available in the API, we are going to close this issue. When it does become available, we will have the CLI and other SDKs support this as we try to do with all API changes. If you notice the API supports this feature in the future and we haven't supported it yet, feel free to re-open this issue.
