### ISSUE TITLE
Feature Request: Folder Upload Report

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#144]
- [X ] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When I upload a folder structure via the folders:upload command there is no progress indicator on the progress but also no report about what was created in a deep structure. The only information being returned is the top level folder created e.g.

Type: folder
ID: '7XXXXXXXXX7'
Sequence ID: '0'
ETag: '0'
Name: <FOLDER NAME>
Created At: '2019-05-02T04:54:08-07:00'
Modified At: '2019-05-02T05:14:35-07:00'
Description: ''
Size: 0
Path Collection:
    Total Count: 2
    Entries:
....

Ideally I would be able to get a CSV/JSON report an everything that was created so that I can use the ID for further work

### Versions Used
Box CLI: 2.x
Operating System: Mac

### Steps to Reproduce
NA

### Error Message, Including Stack Trace
NA

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@jacquesvandermerwe This seems like a good feature; I've added it to our backlog!
