### ISSUE TITLE
Feature Request: Add --update command

### ISSUE THREAD

**Issue by nocomputeruser** [box/boxcli#147]
- [X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Is it possible to add a --update command to update the Box CLI applicaton. It looks like that I would need to reinstall the application to get the update right?

### Versions Used
Box CLI: 2.0

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@abarber229 Yes, currently you'll need to use the installers to update the CLI.  The framework we're using the build the CLI does have the capability to add a `box update` command, or even auto-update, but on our end we'll need to do some work around testing out the update mechanism and hosting the update files.  This is a feature we would love to add, but it's not on our immediate roadmap; I'll update this issue when we start working on it!
