### ISSUE TITLE
Folders: Update command is_collaboration_restricted_to_enterprise not available

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#148]
- [ X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The folder update API has a setting `is_collaboration_restricted_to_enterprise` which controls the setting of who can be invited to a folder. This is not available in the CLI v2.1.0

### Versions Used
Box CLI:2.1.0
Operating System: MacOS Sierra

### Steps to Reproduce
box folders:update -h

### Error Message, Including Stack Trace
NA

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@jacquesvandermerwe Thanks for letting us know about the missing flag; I opened a PR to add it and that should make it into the next CLI release.
