### ISSUE TITLE
PowerShell throws errors for no-json output

### ISSUE THREAD

**Issue by larhape** [box/boxcli#159]
- [x] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When I send a Box-CLI command that does not output data (json), Powershell throws an error. This is not a "real" error as the command is executed and successfully executed. But it seams that, somehow, the output of Box-CLI is interpreted by Powershell and executed, and the error seams to be a consequence of this behavior. But once again, it only happens for command that do not output data, and the job is actually done anyway, no problem on this side.

Example of commands : "box files:download (args)" or "box folders:collaborations:delete (args)". These commands normally output something like "file X downloaded" or "Collaboration X successfully removed".

### Versions Used
```
PS > box --version
@box/cli/2.3.0 win32-x64 node-v11.13.0 

PS > $psversiontable
Name                           Value                                                                                                                                                                      
----                           -----                                                                                                                                                                      
PSVersion                      5.1.14393.3053                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                    
BuildVersion                   10.0.14393.3053                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                                        
SerializationVersion           1.1.0.1   
```

OS : Microsoft Windows Server 2016 (1607)

### Steps to Reproduce
Launch Powershell ISE. In the Powershell part of the ISE, just type a valid command like "box files:download XX" with XX being a valid file id for the default user used by Box-CLI.

Note that the error is not thrown if using CMD or even Powershell (not ISE). However, it is thrown if using Powershell ISE or a scheduled task with action "PowerShell.exe -file (my file.ps1)"

### Error Message, Including Stack Trace
```
PS > box files:download 354974127564 --yes
box : Downloaded file boxUsersFolders.csv
Au caractère Ligne:1 : 1
+ box files:download 354974127564 --yes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Downloaded file boxUsersFolders.csv:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError 
```
All the lines (except the first) are in red, meaning this is an error thrown. Interesting part of it is the first line "box : Downloaded file boxUsersFolders.csv". The text "Downloaded file boxUsersFolders.csv" is the normal (expected) output of the command.

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@larhape I'm not a PowerShell expert, but I believe this is because PowerShell interprets output that the Box CLI writes to `stderr` as indicating an actual error in the command.  The CLI uses `stdout` for data output, and `stderr` for messages, including success messages.  That way, for commands that output both, it's possible to redirect just the data output to a file output or pipe it to some other command.  I found a [StackOverflow thread](https://stackoverflow.com/questions/2095088/error-when-calling-3rd-party-executable-from-powershell-when-using-an-ide) with more information; hopefully that helps!

**Comment by larhape** [comment]
@mattwiller Oooh, thank you. It makes perfect sense. Of course. But this is definitely a problem of conception, IMHO. In previous versions of Box CLI, the message and the data was sent to `stdout` (first, the message, second the data). Ok, it was necessary to detect the beginning of the data, but this was not a big issue, json data starts by [ or {, so it was easy to make the split. If you want data in plain text (no-json), I suppose something can be done to make the split, like "the first line is message, the rest is data", or maybe introduce some "-----BEGINNING OF DATA-----" line... Using `Stderr` to split data and message is a false good idea. `Stderr` is definitely intended to receive errors, it was meant for that ! Otherwise, if there is a REAL error, how can we make the difference ? Using `stderr` that way ruins proper error handling, which is really bad, at least in my view.

Is there a way to fix it ? Or at least to change this default behavior, so that real errors go into stderr and all the rest goes to stdout, just like before ?

But thank you very much for the answer, very helpful, at least I understand what the problem is !!!

**Comment by mattwiller** [comment]
@larhape Despite the name, it's not the case that `stderr` is strictly reserved for error conditions.  The [POSIX standard][posix] says that it's "for writing diagnostic output", and the [libc documentation][libc] agrees that it's "used for error messages and diagnostics issued by the program".  Many CLI tools write non-error output to `stderr`; for example, [curl uses it to output a progress bar][curl-progress].  I'm not sure why PowerShell interprets all `stderr` output as indicating an error, but I suspect it may just be a misalignment between Windows and *nix-based operating systems.  The best way to determine if the CLI has actually encountered an error is through the exit code, which I believe is either `$?` or `$LASTEXITCODE` in PowerShell.  An exit code of `0` indicates a successful command.

That said, I think you should be able to redirect the `stderr` output to `stdout` to avoid triggering the PowerShell behavior you're seeing.  The StackOverflow thread I linked above suggested doing something like `box files:download 354974127564 --yes 2>&1` — does that help at all?

[posix]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/stdin.html
[libc]: https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html
[curl-progress]: https://ec.haxx.se/cmdline-progressmeter.html

**Comment by larhape** [comment]
Yes, it helps a lot, many thanks for that and your patience. I really appreciate @mattwiller.

However, I am afraid I must disagree with your point of view (and your interpretation of Posix). When I read "error messages and diagnostic issued by the program" I understand _the diagnostic issued to explain and/or develop the error messages_, possibly debuging messages, but not just "any" message (and certainly not the "successful" ones). More generally, in my experience, it is never a good idea trying to be smarter than common sense, which is stderr is meant for errors. Doing otherwise might be in the Posix standards eventually, but it will raise issues in the long run.

You said many CLI tools behave that way. Maybe you are right (even though I never noticed that before). In the curl example you gave, I noticed the `--silent` option. Maybe that is the way to go with Box CLI ? To have a silent option in the environment for successful message. Of course, this option should not prevent real errors to be thrown in stderr if an error occurs. It is not ideal, but definitely better than current behavior.

Box CLI is a great tool. I mean it. It is simple, fast, convenient, it integrates seamlessly in all sorts of scripts. I know the scripting guys come from the Linux world. I come from this world as well, I was born with Bash, Awk, ssh, Perl and regular expressions. But in the case of Box, I use Powershell as it is more convenient to manipulate Active-Directory objects and Windows filers. And I must say that Powershell is a good scripting language, it is the scripting language that Windows was lacking for years. I am probably not the only one to use Box CLI with Powershell, and sorry to say that but this way of thinking with the stderr and exit code is definitely something coming from a Linux-brain. I don't like the opposition Linux/Windows, but this is where we are here. Powershell handles errors with try/catch, not with exit codes (even though it is possible). Microsoft will not change Powershell because of Box CLI. In my view, Box CLI should take that into consideration and adapt.

**Comment by mattwiller** [comment]
@larhape I really appreciate the detailed feedback; you've raised some really important points and we can definitely reconsider how we're handling this type of output.  Unfortunately, this isn't a change we'll be able to make across the board right away, but I think a `--silent` or `--quiet` flag sounds like something we could get done.  From a cursory look at other CLI tools like curl and wget, it seems like they typically use such a flag to disable __all output__, but if we want to have the flag just disable success/diagnostic messages I think that should be fine.

So, just to check, would having a `--quiet` flag in the CLI  that disables all non-error messages to `stderr` help make it easier for you to use the CLI with PowerShell?

**Comment by larhape** [comment]
Thank you @mattwiller for this constructive discussion.

By the way, I fully confirmed that what you said in your first post is definitely the reason behind the error. Actually, since your answer, I have adapted my script so that they "ignore" errors (`stderr`) for the verbs that send such things. Fortunately, it's not all of them. I spotted a few ones like `files:download` and several `*:delete` or `*:remove`. Most of the Box CLI actions simply returns (json) data on `stdout` on successful completion and NULL in `stdout` + error message on `stderr` on failure. So, what I did to "ignore" the errors (in some selected cases) was to make a try/catch but with nothing on the catch. Then I simply check by other means if the action was successfully done (I check if the file downloaded is there, I check if the user I have just removed is not there anymore etc.). It is another way to go than the catching the exit code as you suggested.

So, to answer your question, yes, this would help to have a `--silent` option the way you describe, for me and for the other guys using Powershell, I suppose. But only if I still have something on `stderr` in case of failure, otherwise, it will be so silent that it will be impossible to make the difference between success and failure, and it would be more or less the same thing than today.

**Comment by larhape** [comment]
I suppose I can close the thread, is it OK for you or should I leave it open ?

**Comment by mattwiller** [comment]
@larhape Feel free to leave this issue open; that way we can update you here when the new flag is being added!  Also, just in case someone else has the same problem, they can see all of the great context we've assembled here

**Comment by mattroyal** [comment]
@larhape  - I wonder if something like this would help.

If boxcli had an option to return informational results like this embedded in JSON objects or in its normal output (instead of or in addition to the stderr output), it strikes me that this might also be helpful for handling those errors in scripts.

For example, if you try to get a file and get a 404, if boxcli returned that error (instead of nothing), powershell could deal with it this way:

`Try {$f = box file:get 1234 | ConvertFrom-Json}`
`Catch {"Error:  $f.message"}`

Or

`$f = box file:get 1234 | ConvertFrom-Json`
`if ($f.message) {"Encountered message: $f.message"} else {Do-Something}`

I have boxcli configured to always output JSON since PowerShell parses that so well.

Something similar could work with your download example.  In your case boxcli isn't really reporting an error, but a different form of presentation would work better for you.  Two birds with one stone.

**Comment by larhape** [comment]
Yes, it would be better to get the error instead of nothing. The error should have a specific key in the json so the existence of the key would mean ‘error raised’. In your example « message ». But yes, definitely, two birds with one stone !

**Comment by JackCulwell** [comment]
My 2 cents, I agree. the fact that many messages appear in the powershell CLI as if they are errors is disconcerting at the very least. I have had to explain the same to each of my team members who use the CLI that some of these are not errors despite their appearance. I also agree with Larhape that the key should be distinct(ive) so that we can easily parse it from the output both visually and programatically.

**Comment by sujaygarlanka** [comment]
#167 This PR allows you to quiet all informational output to stderr. So only errors will be outputted to stderr. I hope this fixes the issue! Feel free to re-open this does not solve your issue.
