### ISSUE TITLE
Feature Request: Add enterprise settings management, for at least root folder content management

### ISSUE THREAD

**Issue by ispcolohost** [box/boxcli#162]
- [x] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Many of the Box CLI utilities include management of content on behalf of other users by way of an --add-user flag.  Many of these same utilities support managing of content at the root level by specifying a parent folder of zero.  For enterprise users, or otherwise large deployments of Box, Box onboarding staff recommend the use of locking root content management to admin and co-admin accounts only.  If that setting is enabled, the Box CLI commands related to content management in the root of user accounts fail with a forbidden / insufficient permissions errors.

Given Box CLI has no tool for altering that setting, an admin must first log into the web interface, turn the restriction setting off, execute the relevant Box CLI commands while hoping no users of the enterprise do any of their own content creation at the root, then remember to go back to the web interface to turn the setting back to on.

If Box CLI could manage that setting, it could be called via Box CLI just before the content management commands to be called, and then again at the end to reenable.  Or even better, perhaps a concept of disable for the duration of this session, max # of commands, etc.

### Versions Used
Box CLI:   @box/cli/2.3.0 darwin-x64 node-v11.13.0
Operating System: Darwin MBPr.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

### Steps to Reproduce
Set Box enterprise settings to only allow admins/co-admins to create root level content.  Run Box CLI to create content as a user:
box folders:create 0 "Test Root Folder" --as-user=123456
Get a failure:
Unexpected API Response [403 Forbidden | 

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@ispcolohost Unfortunately, this functionality is not yet exposed via the Box API; we're unable to add it to the CLI at this time.  I'll note the feature request, though, and we'll leave this thread open to provide any updates on when this functionality might be available in the future.

**Comment by sujaygarlanka** [comment]
@ispcolohost As this is still not available in the API, we are going to close this issue. When it does become available, we will have the CLI and other SDKs support this as we try to do with all API changes. If you notice the API supports this feature in the future and we haven't supported it yet, feel free to re-open this issue.
