### ISSUE TITLE
Go beyond the limit (100) of returned folders

### ISSUE THREAD

**Issue by larhape** [box/boxcli#163]
- [x] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I did a simple "box folders:get xxx" where xxx is some Folder ID.

It happens that I have one of this folder with many subfolders (more than 100). The problem is that the box folders:get command only returns the first 100 subfolders. To be more precise, in the Json response, inside the "item_collection" hash-table, I have an attribute 'limit' which equals 100 and another one 'total_count' which equals 170. If I count the number of element in the 'entries' array, I have indeed 100 of them.

I cannot figure out how I can get the 70 subfolders missing. I saw nothing that might set the limit to a higher value and I did not saw anything neither that could retrieve the remaining entries in a second run. I need the full list (at least the folder ids), not just the first 100.

### Versions Used
@box/cli/2.3.0 win32-x64 node-v11.13.0 
Windows-Server 2016 version 1607

### Steps to Reproduce
Put more than 100 subfolders in a single folder and try to get them all by "box folders:get"

### Error Message, Including Stack Trace
No error message

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@larhape The `box folders:get` command is intended to get information about a single folder; the `item_collection` property of the folder is only a "preview" of the items in that folder.  To retrieve the full set of items in the folder, use the `box folders:items` command instead.

**Comment by larhape** [comment]
Aouchh. Stupid me. Yes, of course !
Sorry for the disturbance, and many thanks for the prompt answer : it definitely solves my problem

**Comment by mattwiller** [comment]
@larhape No worries — there are a lot of different commands in the CLI!  I'm glad it's working for you now 🙂
