### ISSUE TITLE
Feature request: Get trashed file

### ISSUE THREAD

**Issue by mattroyal** [box/boxcli#169]
- [ X ] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
boxcli doesn't seem to support the "Get Trashed File" call (or if it does, I can't find the function):

https://box.dev/en/reference/get-files-id-trash/

We have accounts that have thousands of files in trash, and it is nearly impossible to recover these from the web UI.  boxcli would be a great alternative.

### Versions Used
Box CLI:  @box/cli/2.1.0 win32-x64 node-v10.10.0

**Comment by nidoran** [comment]
Hi @mattroyal ,

Yes, boxcli doesn't have this feature right now. I created a ticket in our backlog to add this. Thanks for bringing this up.

**Comment by cbass27** [comment]
Is it a missing feature or a bug? I just assumed it was a bug thinking a loop somewhere in code wasn't set correctly and missing the last version.

**Comment by PJSimon** [comment]
Closing, as it was resolved in #179.
