### ISSUE TITLE
Question: Does Box CLI support bulk actions for read-only operations?

### ISSUE THREAD

**Issue by mattroyal** [box/boxcli#170]
- [x] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Box CLI supports bulk actions from CSV or JSON files when items are being updated.  Are bulk actions available for read-only operations like folders:get ?  And if so, what format do I need?

For example, I try this:
`box folders:get --bulk-file-path items.csv --fields id,name,owned_by,parent --csv --save-to-file-path results-output.csv --as-user $userid`

My items.csv file is a single-column CSV of folder IDs, with the header "id".
However, it still asks for a folder ID.

```
Missing 1 required arg:
id  ID of folder to get; use 0 for the root folder
See more help with --help
```

I can script this through powershell, but if Box CLI does support batch operations like this, sometimes I would like to try to use its built-in capabilities.

### Versions Used
Box CLI: '@box/cli/2.1.0 win32-x64 node-v10.10.0'

**Comment by sujaygarlanka** [comment]
I believe the issue is the missing equals sign to specify flags. The command should be: box folders:get --bulk-file-path=items.csv --fields=id,name,owned_by,parent --csv --save-to-file-path=results-output.csv --as-user=$userid

Any command in the CLI that has Bulk flags should support Bulk actions.
