### ISSUE TITLE
files:versions doesn't list most recent version

### ISSUE THREAD

**Issue by cbass27** [box/boxcli#174]
- [ X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When running box files:versions id, the versions that are listed doesn't include the most recent version.
Uploaded a file using box-cli without issue. I'm able to retrieve folders and files without issue. But when I use versions (ex. box files:versions <fileid>), the output does not include the most recent version that was uploaded. I tested with uploading multiple versions of the exact same file, without modifications that is.

### Versions Used
Box CLI: @box/cli/2.4.0 linux-x64 node-v8.10.0
Operating System: Ubuntu 18.04 x64

### Error Message, Including Stack Trace
 box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.19 argv: [ 'files:versions', 'changedforprivacy', '--verbose' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings { boxReportsFolderPath: '/home/testuser/Documents/Box-Reports',
  box-cli:init   boxReportsFileFormat: 'txt',
  box-cli:init   boxDownloadsFolderPath: '/home/testuser/Downloads/Box-Downloads',
  box-cli:init   outputJson: false } +2ms
  box-cli:init Using environment default { clientId: 'changedforprivacy',
  box-cli:init   enterpriseId: 'changedforprivacy',
  box-cli:init   boxConfigFilePath: '/home/testuser/box/boxcli-2.4.0/config.json',
  box-cli:init   hasInLinePrivateKey: true,
  box-cli:init   privateKeyPath: null,
  box-cli:init   name: 'default',
  box-cli:init   defaultAsUserId: null,
  box-cli:init   useDefaultAsUser: false,
  box-cli:init   cacheTokens: true } +8ms
  box-cli:init Initialized client from environment config +13ms
  box-cli:execute Starting execution command: files:versions argv: [ 'changedforprivacy', '--verbose' ] +0ms
  box-cli:output Unrolled iterable into 2 entries +0ms
  box-cli:output Formatted output content for display +3ms
  box-cli:output Using txt output format +3ms
  box-cli:output Processed collection into human-readable output +18ms
  box-cli:output Writing output to terminal +2ms
----- File Version 582731418881 -----
Type: file_version
ID: '582731418881'
SHA1: 6a46e8c0efae86a4169383caab14c5a4f63f4f30
Name: utstring.h
Size: 12230
Created At: '2019-10-31T18:47:55-07:00'
Modified At: '2019-10-31T18:47:55-07:00'
Modified By:
    Type: user
    ID: 'changedforprivacy'
    Name: getcald
    Login: AutomationUser_905711_j6vHG2L5QX@boxdevedition.com
Trashed At: null
Purged At: null

----- File Version 582045765161 -----
Type: file_version
ID: '582045765161'
SHA1: 6a46e8c0efae86a4169383caab14c5a4f63f4f30
Name: utstring.h
Size: 12230
Created At: '2019-10-30T23:04:45-07:00'
Modified At: '2019-10-30T23:04:45-07:00'
Modified By:
    Type: user
    ID: 'changedforprivacy'
    Name: getcald
    Login: AutomationUser_905711_j6vHG2L5QX@boxdevedition.com
Trashed At: null
Purged At: null
  box-cli:output Finished writing output +44ms

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by cbass27** [comment]
Maybe I'm not understanding the actual usage of files:versions. Is the intended usage to just show versions of the file that aren't the current or most recent version?

**Comment by sujaygarlanka** [comment]
@cbass27 Sorry for the delayed response. files:versions will return all the versions of the file other than the current one. To get the current one, you should use files:get. Hope this helps!
