### ISSUE TITLE
Missing or undocumented uninstaller/uninstall method

### ISSUE THREAD

**Issue by nicolaevladescu** [box/boxcli#177]
- [x] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
How do you uninstall the boxcli on macOS ?

### Versions Used
Box CLI: `@box/cli/2.4.0 darwin-x64 node-v12.6.0`
Operating System: macOS Catalina

### Steps to Reproduce
1. Install from `.pkg`.
2. Try to uninstall.

### Error Message, Including Stack Trace

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
__Step 1:__ Delete the cli folder at the following path `usr/local/lib/@box/cli`
__Step 2:__ Run `sudo pkgutil --forget com.box.cli`
