### ISSUE TITLE
Add --ignore flag for box:folders:upload

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#178]
- [X ] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When you use the folders upload it works perfectly for a first time load because none of the folder objects exists. However if you 'add' additional folders and then execute the upload again, it will throw a 409 already exist for the existing folders. An ignore flag to ignore 409 errors will allow the tools to continue to create the missing folders without stopping the command.

### Versions Used
Box CLI: 2.4

### Steps to Reproduce
Create a folder structure on the local machine and execute box:folders:upload for that structure. Append additional folder to the same structure and execute command again. The CLI will raise a 429 as soon as it encounters a previously created folder with the same name and then terminate with a 409.

### Error Message, Including Stack Trace
409 Item already exists

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
Currently we do not have the feature to upload an existing folder to update it. It requires some code changes, so we will put on our to do list.

**Comment by PJSimon** [comment]
@jacquesvandermerwe, let us know if you need anything else!  Thanks!
