### ISSUE TITLE
--as-user header flag fails in bash script

### ISSUE THREAD

**Issue by DJLeanix** [box/boxcli#181]
- [x] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Hi,

I've created a small script to move several folders at once in the name of other users with the --as-user flag, but I'm getting this error:
Invalid character in header content ["As-User"]

I rant the script already with bash and sh both the same error.

### Versions Used
Box CLI: 2.4.0

### Steps to Reproduce
This is my script:
`#!/bin/bash

#specify CSV
INPUT_FILE='foldermovetest.csv'

#backup IFS and change IFS to delimiter ","
OIFS=$IFS;
IFS=",";

while read -r folderid newparentid userid
do

/usr/local/lib/@box/cli/bin/box folders:move "$folderid" "$newparentid" --as-user="$userid"

echo "$folderid moved to $newparentid in the name of $userid"

done < $INPUT_FILE

#change IFS back to Default
IFS=$OIFS`

### Error Message, Including Stack Trace
Invalid character in header content ["As-User"]

[cli-docs]: https://github.com/box/boxcli#command-topics
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
@DJLeanix sorry about the trouble you're having here.  We'll get back to you ASAP to try to resolve this for you.

**Comment by sujaygarlanka** [comment]
@DJLeanix Can you give us the user ID you are trying to pass? This will help us determine whether the CLI has an issue by not being able to pass in valid user IDs.

**Comment by DJLeanix** [comment]
@sujaygarlanka they were normal number values which I've exported from BOX admin center

**Comment by sujaygarlanka** [comment]
@DJLeanix I believe it's failing because when you read the CSV, you are getting every line of the CSV. This means you get the first line as well, which is the column names. In your script, since you run the box command for every line, you pass in the column names as values for the Box command. These values are not valid Box folder IDs and user IDs. I would put something in your script to skip running the Box command for the first line.

**Comment by sujaygarlanka** [comment]
I hope this solves your issue! If you have any questions regarding this issue, you can re-open it.
