### ISSUE TITLE
Documentation doesn’t' reflect the changes added in version 2.5.1

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#192]
- [ X] I have checked that the [CLI documentation][cli-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Version 2.5.1 has been deployed but the documentation is still reflecting 2.4.0 commands e.g. there is no reference of the trash:restore commands.

### Versions Used
Box CLI: 2.5.1
Operating System: Mac Catalina

**Comment by sujaygarlanka** [comment]
#193
