### ISSUE TITLE
Can't install on MacOS without security override

### ISSUE THREAD

**Issue by ispcolohost** [box/boxcli#199]
Running a fresh install of MacOS 10.15.5 Catalina, Box CLI won't install without having to override security settings:

<img width="532" alt="Screen Shot 2020-06-23 at 6 15 49 PM" src="https://user-images.githubusercontent.com/10602304/85471216-233e1780-b57e-11ea-9e8f-5f03b1848fc4.png">

Can the CLI installer get the same signing Box's other Mac apps have to prevent this issue?  Would definitely make my staff more comfortable if it were downloadable from the official Box website, since no way to know who has update access to github.

**Comment by PJSimon** [comment]
Hi @ispcolohost ,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by sujaygarlanka** [comment]
Jira ticket: SDK-1441
