### ISSUE TITLE
CLI search for specific string doesn't match web app

### ISSUE THREAD

**Issue by weigh2tall** [box/boxcli#205]
If you are trying to search for a specific string that contains special characters (specifically the underscore), but no spaces the CLI does not allow you double quote the string and search for that specific string.  If the string has a space in it, double quotes work. 

Examples of searches that produce the error:
    "Project_Dual_Rings"
    ""Project_Dual_Rings"" (trying to double quote)
    '"Project_Dual_Rings"'  (Single quote, then double quote)
    `"Project_Dual_Rings`" (powershell escape character, then quotes)

In each Box CLI verbose shows the submitted query as 'Project_Dual_Rings' this will return results that match Project, Dual and Rings.  
If searching via the webapp, I can put the normal double quotes around the string and receive the expected results. 

Enable the use of double quoted strings where there are no spaces in the string

I've tried forcing encapsulating the search term in additional quotes or escape characters, none have been effective.

I can provide a verbose screenshot if needed, but it's fairly easy to reproduce this
I have brought this up in the Box Developer forum
https://support.box.com/hc/en-us/community/posts/360049150994-CLI-Search-for-exact-match

**Comment by sujaygarlanka** [comment]
@weigh2tall If you want to include special characters, using an escape character should work. For example `box search \"test.txt\"`. I tried this locally on a Mac terminal and it was working for me. For Powershell, this seemed to work box search \`"test.txt\`". I am not familiar with Powershell, but used the following [resource](http://www.rlmueller.net/PowerShellEscape.htm#:~:text=DirectoryServices.,and%20ADO%20both%20use%20ADSI.) to help me out. I hope this helps. If you continue to have an issue, feel free to re-open this.
