### ISSUE TITLE
Feature Request: Add more data to "Shared_Link" section of Box File:Get (last preview, last download, link creation date))

### ISSUE THREAD

**Issue by scarymike23** [box/boxcli#208]
I was hoping to do a bit of a Share link cleanup effort, but I wanted to base it on the last time it was used and when it was created. Unfortunately, it doesn't seem like that data is available.

I know that previews and downloads are time stamped (you can see them in the Web GUI), so I was hoping we could get that data added tot he "Get"

Of course, that doesn't help with "Folders" shared links, as they never show preview and downloaded counts. So instead, is there a "last time this link was used" option would be even better? 

Obviously, "Link creation date" would be super handy too, but I don't know if you guys store that or not. 

Example (bold = request):
Shared Link:
    URL: 'https://subdomain.box.com/s/randomstringofchars'
    Download URL: 'https://subdomain.box.com/s/randomstringofchars.xlsx'
    **Link Created On: '2020-09-17T14:31:59-07:00'**
    Vanity URL: null
    Vanity Name: null
    Effective Access: company
    Effective Permission: can_download
    Is Password Enabled: false
    Unshared At: null
    Download Count: 8
   **LastDownload: '2020-09-17T14:31:59-07:00'**
    Preview Count: 4
    **LastPreview: '2020-09-17T14:31:59-07:00'**
    **Last time Link was accessed: '2020-09-17T14:31:59-07:00'**
    Access: company
    Permissions:
        Can Preview: true
        Can Download: true

**Comment by sujaygarlanka** [comment]
@scarymike23 These features are currently not available in the API and the SDK is a wrapper around the API, so we cannot have the SDKs produce this information. I recommend filing the feedback [here](https://pulse.box.com/forums/909778-help-shape-the-future-of-box). This is a direct line to the product team who determine API features. I hope this helps!
