### ISSUE TITLE
macOS packaging: Apple Developer certificate used to sign releases is expired

### ISSUE THREAD

**Issue by maxfierke** [box/boxcli#221]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Installing on macOS shows that the Developer certificate used to sign the executable/pkg file expired in January of 2020.
This doesn't give me confidence that its safe to run this on my machine. If you bypass the cert (i.e. "accept" its expiredness), the install still fails because the package is "untrusted". 

### Steps to Reproduce
- Download boxcli v2.7.0 macOS pkg
- Hold option & double-click to open, accepting "Open" at security dialog about the package not being verifiable (see #199, for related issue)
- Installer.app will warn about the certificate being expired

### Expected Behavior
Not see a cert error when trying to install

### Error Message, Including Stack Trace
N/A

### Screenshots
<img width="745" alt="Screen Shot 2020-12-03 at 8 58 17 AM" src="https://user-images.githubusercontent.com/354236/101045325-d0618680-3545-11eb-85fc-f6bae92a189b.png">

### Versions Used
Box CLI: 2.7.0
Operating System: macOS 10.15.7

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@maxfierke We are fixing this issue and cutting new release today.

**Comment by sujaygarlanka** [comment]
@maxfierke New release is out valid certificate. Sorry for any inconvenience!
