### ISSUE TITLE
box folders:move times out when moving larger folders e.g. over 2GB

### ISSUE THREAD

**Issue by cloudhal** [box/boxcli#223]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Just move a folder (once both users are owners) using folders:move. This just hangs every time with larger folders, even though the folder itself does move. Running the command a second time then completes.

### Steps to Reproduce
Move a folder

### Versions Used
Box CLI: @box/cli/2.7.0 win32-x64 node-v15.0.1
Operating System: Windows Server 2016

**Comment by sujaygarlanka** [comment]
@cloudhal Sorry for the delay. Is this still an issue?

**Comment by cloudhal** [comment]
@sujaygarlanka yes but I think this only happens when using BoxCLI from Powershell.
