### ISSUE TITLE
[question] Does boxcli support app token(server authentication) auth in box cli?

### ISSUE THREAD

**Issue by invent-lwj** [box/boxcli#226]
Hi, I want to access by app token(server authentication). 
Does app token(server authentication) is supported?
Thanks!

**Comment by knmeiss** [comment]
The only authentication method that is supported for use with the CLI is JWT. App token auth has [limited API capabilities](https://developer.box.com/guides/authentication/app-token/endpoints/) and is used if you want to leverage [Box's preview services](https://developer.box.com/guides/embed/box-view/), but don't need components like permissions, user model, file/folder structure.

**Comment by invent-lwj** [comment]
@knmeiss  Thanks for your replay!
I'm try to call boxcli with `--token`, but fail, cloud you provide some suggestion? Thanks!
This is my error #227
