### ISSUE TITLE
box user events fails in CLI

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#229]
- [ X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When issuing the following event
`box events --as-user <user_id>` the call never returns. We then tried the following 
`box events -t <user_specific_token>` and this also failed. 

We can however issue the following in Postman and it works as expected. This is the CURL representation
`curl --location --request GET 'https://api.box.com/2.0/events?limit=100' --header 'Authorization: Bearer <service account_token>' --header 'As-User: <user_id>'` OR `curl --location --request GET 'https://api.box.com/2.0/events?limit=100' --header 'Authorization: Bearer <user_specific_token>' ` and it will work as expected returning results

### Steps to Reproduce
See steps above

### Expected Behavior
We expected the CLI to return results.

### Error Message, Including Stack Trace
No error is shown, but no results are returned and it looks like it loops.
See Verbose trace
`  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'events', '-t', '<token>', '-v' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings {
  box-cli:init   boxReportsFolderPath: '/Users/jvandermerwe/Documents/Box-Reports',
  box-cli:init   boxReportsFileFormat: 'txt',
  box-cli:init   boxDownloadsFolderPath: '/Users/jvandermerwe/Downloads/Box-Downloads',
  box-cli:init   outputJson: false,
  box-cli:init   enableProxy: false,
  box-cli:init   proxy: { url: null, username: null, password: null }
  box-cli:init } +1ms
  box-cli:init Using passed in token <token> +2ms
  box-cli:execute Starting execution command: events argv: [ '-t', '<token>', '-v' ] +0ms`
### Versions Used
Box CLI: 2.8
Operating System: macOS Catalina 10.15.7

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by swfree** [comment]
Hi @jacquesvandermerwe thanks for filing this issue, I'll create a ticket in our backlog to fix this. It looks like the code is expecting the `stream-position` parameter to be present. When I run `box events` I also get stuck in a loop, but when I run `box events --stream-position=now` it returns as expected. To unblock you while we work on the fix, try passing in the `stream-position` parameter (see [docs](https://developer.box.com/reference/get-events/#param-stream_position) for possible values).
