### ISSUE TITLE
Metadata Templates: copyInstanceOnItemCopy parameter not available

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#235]
### Is your feature request related to a problem? Please describe.
The CLI doesn't support copyInstanceOnItemCopy when creating or updating metadata templates. This feature is used to ensure that items with this template attached also copies the metadata template when a copy of the folder or file is made. 

### Describe the solution you'd like
Ability to set the parameter via CLI rather than having to revert to Postman/API

### Describe alternatives you've considered
Postman/API/Curl

### Additional context
https://developer.box.com/guides/metadata/templates/update/

**Comment by sujaygarlanka** [comment]
Hello @jacquesvandermerwe, This is on our backlog. We will get to this as soon as possible. Thanks!

**Comment by sujaygarlanka** [comment]
Added with #239,
