### ISSUE TITLE
can't use folders:upload in the latest version, 2.9.0

### ISSUE THREAD

**Issue by ZhyeYin** [box/boxcli#238]
- [X ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I downloaded the latest release but still can't use folders:upload capability. See the version of box CLI I used and the error output. This is related with the previous issue currently closed(#231). 

### Steps to Reproduce
My colleague and I tested 2 different linux servers we owned. We were able to reproduce at least in our site.

### Error Message, Including Stack Trace
BoxCLIError: Could not upload file tmp_jed3/small_file.txt
Caused by: Error: ESOCKETTIMEDOUT
at ClientRequest. (/projects/projects_crt/tools/boxcli-master/node_modules/request/request.js:816:19)
at Object.onceWrapper (node:events:482:28)
at ClientRequest.emit (node:events:376:20)
at TLSSocket.emitRequestTimeout (node:_http_client:787:9)
at Object.onceWrapper (node:events:482:28)
at TLSSocket.emit (node:events:376:20)
at TLSSocket.Socket._onTimeout (node:net:481:8)
at listOnTimeout (node:internal/timers:556:17)
at processTimers (node:internal/timers:499:7)

### Versions Used
Box CLI: @box/cli/2.9.0 linux-x64 node-v15.5.1
Operating System: Ubuntu 16.04.4

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by swfree** [comment]
Hi @ZhyeYin, thank you for testing this out! The fix for box folders:upload to function was to package the CLI with Node v14. Since your version is running node-v15.5.1 it looks like I only made that change for the Mac package. I'll work on fixing this for the Windows installers!

**Comment by ZhyeYin** [comment]
> Hi @ZhyeYin, thank you for testing this out! The fix for box folders:upload to function was to package the CLI with Node v14. Since your version is running node-v15.5.1 it looks like I only made that change for the Mac package. I'll work on fixing this for the Windows installers!

hi, @swfree
That sounds awesome! You mean Ubuntu installers, I assume?

**Comment by swfree** [comment]
Good catch @ZhyeYin! Do you install the CLI by running `npm install --global @box/cli`? I believe the CLI runs with your system's Node version in that case. If your Node version is v15.5.1, could you try downgrading your Node to v14 and try again? We plan to support Node v15 in the future, but we're using this solution in the short term.

**Comment by packj** [comment]
I think I installed node and box cli for Zhye, but I didn't make notes on how I did that and it was weeks ago... I don't think I used "--global" when I did the npm install... should we do that?  there is very little info on how to install box cli on the website.

**Comment by packj** [comment]
ok... downgraded to node 14.16.0

**Comment by ZhyeYin** [comment]
Thanks, @packj!
@swfree, I also downgraded to node 14 and I'm able to use folders:upload!

**Comment by swfree** [comment]
Awesome, glad to hear that worked @ZhyeYin! I'll close this issue since this is the current solution, but we also have on our backlog to support Node v15 in the future as well.
