### ISSUE TITLE
"Failed creating CLI working directory" when adding the path to the environment

### ISSUE THREAD

**Issue by Giorgosi** [box/boxcli#241]
After installation of boxcli I try to add the json configuration file as referred in the installation steps using the cmd: 
box configure:environments:add [PATH_TO_CONFIG_FILE]

I receive the following error message:
"Failed creating CLI working directory"

Using the command: Box configure:environment:get I receive the same error message.

- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Versions Used
Box CLI: 
Operating System: 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@Giorgosi Could you run the same command but with `DEBUG=*` before it like, `DEBUG=* box configure:environments:add [PATH_TO_CONFIG_FILE]` and copy and paste the output in this issue. Also, what system are you using. Is it Mac or Windows?

**Comment by Giorgosi** [comment]
I'm using Windows. After running the command with DEBUG=* I obtain the followig message:
'DEBUG' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tvidal-net** [comment]
I know the issue is closed, but I had the same issue and just for future reference in case someone else find this through google.

This happens if you have any non-existing directory in your box cli configuration under `~/.box`. I moved the box files directory location and the previous one was still set in the config. Changing the `settings.json` to use the new directory has fixed the issue.
