### ISSUE TITLE
Bulk Box users search not working from email lookup

### ISSUE THREAD

**Issue by nexus667** [box/boxcli#242]
I have a list of email address that I wish to lookup the account id.

Error:
2 entries failed!
----------
Entry 1 (

) failed with error:
Missing 1 required arg:
name  Name of user to search for
See more help with --help

----------
Entry 2 (

) failed with error:
Missing 1 required arg:
name  Name of user to search for
See more help with --help

I had to insert name label at the top of list versus using no label or login label

**Comment by PJSimon** [comment]
Hi @nexus667,

I think your csv file has two lines, one for each email address you are looking up.  You need to add a header line at the top of the CSV with the value `name`.  Give that a try and let us know how it works for you.

Thanks,

@PJSimon
