### ISSUE TITLE
writing tracking_codes via CLI?

### ISSUE THREAD

**Issue by Michael-B-23** [box/boxcli#249]
Is it possible to update tracking_codes via CLI? 

I managed to read tracking codes using Box users:get, but I can't figure out how to write into those fields. 
box users:get IDHERE --fields="tracking_codes,name" 
will bring them back. 

But  box users:update does not seem to have an option for writing to tracking_codes. 

Thank you!

**Comment by mwwoda** [comment]
Hey @Michael-B-23 

Thanks for reaching out to us! I see that we currently do not support tracking codes for users in create and update commands in the CLI. I created a ticket for this and put in our backlog (SDK-1706). Currently we do not have a time frame for this, but as soon as we will have I'll let you know.

Thanks @mwwoda

**Comment by congminh1254** [comment]
Hi @Michael-B-23 

We have just release the BoxCLI version 3.10, including tracking codes for create and updating users.

Regards,
Minh
