### ISSUE TITLE
Box Metadata Query Support

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#256]
### Is your feature request related to a problem? Please describe.
Please support Box Metadata Query. Customers want to be able to export the results to a CSV file.

### Describe the solution you'd like
Execute Box Metadata Query and export results to CSV file

### Describe alternatives you've considered
Custom development

**Comment by PJSimon** [comment]
Thanks @jacquesvandermerwe!  This is on our roadmap (SDK-1418) and we will prioritize it in the next sprint or two.
