### ISSUE TITLE
How can I get file or folder ID ?

### ISSUE THREAD

**Issue by wyim-pgl** [box/boxcli#257]
### Description of the Issue
How can I get file or folder ID ?
### Steps to Reproduce
NA

### Screenshots
![image](https://user-images.githubusercontent.com/907041/130147350-ceeb36af-7b62-4ff9-b4b0-f763220d4920.png)

### Versions Used
Box CLI: box/cli/2.9.0 linux-x64 node-v12.4.0
Operating System: Linux login-0 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mhagmajer** [comment]
Hi @wyim-pgl! Can you explain more what you are trying to do with the CLI?

**Comment by mgrytsai** [comment]
Closing this ticket due to inactivity.

FYI to get folder ID using CLI you can use `box folders:items` command. For example, to list all folders and get folder ID for root folder is `box folders:items 0`
