### ISSUE TITLE
Download shared folder

### ISSUE THREAD

**Issue by biocyberman** [box/boxcli#266]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I got errr for the command below
```
box folders:download 144 # ID of a folder that is shared to me.
Unexpected API Response [404 Not Found | asdasdhasdahdasdfasdhahdasd] not_found - Not Found
```

### Expected Behavior
Be able to download the folder to my local machine. Alternatively, I should be able to use `curl` or `wget` to download the folder with the shared link.

### Versions Used
Box CLI: `@box/cli/2.9.0 linux-x64 node-v16.6.1`
Operating System: Ubuntu 18.04

**Comment by mwwoda** [comment]
Hi @biocyberman 

To download a file that has been shared with you using Shared Links through API, please refer to [this guide](https://developer.box.com/guides/downloads/shared-link/). The process is slightly different than a normal download.

AFAIK we don't support downloads using shared links in BoxCLI at the moment. You can use the curl samples in the documentation I linked or try using `box request` command to implement custom request.

Thanks,
Mateusz

**Comment by biocyberman** [comment]
@mwwoda 

I created a test directory on my own account:
Folder link: https://app.box.com/folder/150744142852 
Folder shared link: https://app.box.com/s/9alg80kaqluqvvrjdgxwkvq9v4oxzyw1

The two links above are real. Could you show me hown to download with `curl` or with `box request`?

I tried the curl example without luck. 
My curl command looks like the following:

```
curl -i -X GET "https://app.box.com/folder/150744142852 " \
     -H "Authorization: Bearer lG2dBOxxSDDoMrkZPRXpOt3EeGVs" \
     -H "BoxApi: shared_link=https://app.box.com/s/9alg80kaqluqvvrjdgxwkvq9v4oxzyw1" \
     -L -o test_dir
```

`test_dir` from this command turns out to be a sign in request page, not a folder as expected. 

The documentation for the API is quite confusing in general due to the differences of main URLs and the process of getting `ACCESS_TOKEN` is poorly described. I ended up using the developer token to test.

**Comment by biocyberman** [comment]
Looks like for a folder I have to create a `POST` request to create a zip file and then download that zip file. I can't still make it to work:

Documentation page:
https://developer.box.com/reference/post-zip-downloads/
```

curl -i -X POST "https://api.box.com/2.0/zip_downloads" \
     -H "Authorization: Bearer YD6gtACgasdfa9adasdajSl88VXx" \
     -d '{
       "download_file_name": "test_dir",
       "items": [
                  {
           "type": "folder",
           "id": "150744142852"
         }
       ]
     }'
```

Returned the following instead of JSON output containing zip file for download:
```
HTTP/2 401
date: Tue, 23 Nov 2021 22:13:57 GMT
x-envoy-upstream-service-time: 353
strict-transport-security: max-age=31536000
box-request-id: 01589616a04baffe9148373baea2e9b1e
```

**Comment by mwwoda** [comment]
If you want to download the contents of a folder using a shared link, you must enumerate the files one-by-one and download them separately. It's not possible to download the entire folder this way.

You can get the content of this folder by calling the `/folders/{folderId}/items` endpoint like this
 ```
curl -i -X GET "https://api.box.com/2.0/folders/150744142852/items" \
     -H "Authorization: Bearer <Token>" \
     -H "BoxApi: shared_link=https://app.box.com/s/9alg80kaqluqvvrjdgxwkvq9v4oxzyw1"
```

This will return ids of the files inside this folder. You can then call download on each of them. So the example curl for a single file would look like this

```
curl -i -X GET "https://app.box.com/files/888201304524/content " \
     -H "Authorization: Bearer <TOKEN>" \
     -H "BoxApi: shared_link=https://app.box.com/s/9alg80kaqluqvvrjdgxwkvq9v4oxzyw1" \
     -L -o downloadedFile
```

I don't think that downloading zip with a share link is possible at the moment. 401 error you posted indicates problem with your token.

**Comment by biocyberman** [comment]
That looks clearer. 
Is it correct that the `GET` URLs for the first and second `curl` commands have different base URL? 
`https://api.box.com/2.0/` vs `https://app.box.com/`?

**Comment by mwwoda** [comment]
Both urls should work, but it's better to stick with `https://api.box.com/2.0` in both API calls.

**Comment by mgrytsai** [comment]
Hi @biocyberman,

Just thought of checking if you still have questions regarding the original topic?
