### ISSUE TITLE
box CLI does not correctly handle certain special characters in JSON output:  – or  •  

### ISSUE THREAD

**Issue by nathaneig** [box/boxcli#269]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
box CLI version 2.9.0 on Windows JSON output does not successfully handle certain characters:
- long hyphen character:  –  (encodes as: â€“ )
- Mac-centric dot character:  •  (encodes as: ΓÇó )
- Possibly other characters but I did not exhaustively search, and rather just shared what I have encountered across the account so far.  It is my hope an adjustment to character encoding/handling will address both these characters and hopefully all others which I have not yet encountered.

### Steps to Reproduce
1. Create a box file or folder with either or both of these characters in the file/folder name:  – or  •  
2. Run either of the following for the file itself or the parent folder respectively:
       box files:get --as-user <userID> <fileID> --json
       box folders:get <parentFolderID> --as-user=$asUserID --json

3. For box files:get, examine the "name" attribute returned in the JSON object and not the character encodings
4. For box folders:get, expand item_collection, expand entries, and for the entry for the respective file, note the "name" attribute and the character encoding for the special characters noted above.

### Expected Behavior
Ideally, these characters would be preserved as they are supported by the Box web GUI and by the operating system

### Error Message, Including Stack Trace
Not applicable

### Screenshots
![boxcliJSONoutput](https://user-images.githubusercontent.com/58782714/148699584-81e8ebca-ab74-494d-8625-591678dfc0fa.png)
![boxWebGUI](https://user-images.githubusercontent.com/58782714/148699585-6e047a6b-fae8-422d-b848-a1c849339e49.png)

### Versions Used
Box CLI: 2.9.0
Operating System: Tested on Windows Server 2016 and 2019

Thanks!

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by arjankowski** [comment]
Hi @nathaneig,

Unfortunately I cannot reproduce this issue on my machine with Windows 10,  it's always displays correts characters. 

It may be a problem with current code page you are using.
So can you check in your Window PowerShell console which code page you are using (type `chcp` in console or check in Properties->Options-> Current code page)?

Can you change code page to `65001`(UTF-8) and check the box api call again?

**Comment by nathaneig** [comment]
Thanks for checking and providing another direction for testing.  It appears this is a Windows centric bug in that old school Windows command shell produces the correct output, Powershell Core version 7 shell produces the correct output, a stand-alone Powershell 5.1 produces the correct output, but the Powershell 5.1 ISE mangles the output as does Powershell 5.1 when called by our automation platform.

Thanks for looking into my report but it appears you can swiftly close this bug report as a false positive as this seems to come down to a historical Windows Powershell issue that is best addressed by us modernizing our automation platform which is easier said than done.

My apologies for sending you on a wild goose chase and thanks again for your consideration and review.
