### ISSUE TITLE
Proxy settings does not work with "box login" with OAuth

### ISSUE THREAD

**Issue by kazunoriobata** [box/boxcli#283]
### Is your feature request related to a problem? Please describe.
It seems proxy settings (url, username, password) do not work with "box login" command. (OAuth login)
Is it a bug or limitation of 3.0.0?

### Describe the solution you'd like
Proxy settings work with "box login" command.

Best regards,
Kazunori Obata

**Comment by mwwoda** [comment]
Hi @kazunoriobata 

Thanks for reaching out to us! It looks like the proxy is not currently supported for OAuth 2.0. I have added this to our backlog (SDK-2049). I will let you know if there are any updates.

Regards,
Mateusz Woda

**Comment by arjankowski** [comment]
The fix for this issue #303 has already been released in version 3.1.0
