### ISSUE TITLE
tokens:get for oauth login

### ISSUE THREAD

**Issue by kobay** [box/boxcli#286]
### Is your feature request related to a problem? Please describe.

It seems `box tokens:get` doesn’t work after `box login` (oauth)

I’m not sure if this is a bug or not, but I hope `tokens:get` is supported for oauth as well, because I sometimes need to execute some apis that are not supported by cli yet and `tokens:get` is handy for that purpose. 

the command executed: 

```
box tokens:get -u 18449512707
```

then returned: 

```
Cannot read property 'keyID' of undefined
```

**Comment by congminh1254** [comment]
Hi,
The command `box tokens:get` only work with JWT auth, and it will not work with OAuth auth from `box login`. We just have small fix to show the correct error when using that command on OAuth.
Please see this PR for more information: box/box-node-sdk#750

Best,
Minh Nguyen Cong
