### ISSUE TITLE
Box CLI "-q" commandlet does not quiet output when using box users:transfer-content

### ISSUE THREAD

**Issue by jkhancock31** [box/boxcli#287]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When attempting to use the "-q" commandlet with box users:transfer-content $OldUserID $NewUserID -q, the output is not quieted and I still see the output of data transferred from one account to another. However, the [documentation](https://github.com/box/boxcli/blob/main/docs/users.md#box-userstransfer-content-userid-newuserid) with the CLI states this is possible. 

### Steps to Reproduce
Run the CLI commandlet box users:transfer-content $OldUserID $NewUserID -q. The output will not be quieted.

### Expected Behavior
I expect the commandlet to complete successfully, but not give me the output showing what data has been moved.

### Error Message, Including Stack Trace
No error message applicable.

### Versions Used
Box CLI: @box/cli/2.6.0 win32-x64 node-v14.8.0
Operating System: Windows 10

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by antusus** [comment]
Hi @jkhancock31 ,

Thanks for submitting this Issue! We are aware that `quiet` flag is added to all methods by default and only handful are supporting this flag. I'm creating internal ticket to address this issue.

@antusus
