### ISSUE TITLE
Error: ESOCKETTIMEDOUT  when executing box:files upload

### ISSUE THREAD

**Issue by fantasyado** [box/boxcli#298]
- [ Yes] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ Yes] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ Yes] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ Yes] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
 I just start to play with box-cli following the official tutorial and everything works fine (e.g. list folder, create folder) until I tried to upload a file using command box files:upload . 

### Steps to Reproduce
 execute the command  **sudo box files:upload /Users/ndu/Downloads/my.png -p 159411462676 --json -v**

### Expected Behavior
the file should be uploaded successfully

### Error Message, Including Stack Trace
  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'files:upload', '/Users/ndu/Downloads/my.png', '-p', '159411462676', '--json', '-v' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings {
  box-cli:init   boxReportsFolderPath: '/Users/ndu/Documents/Box-Reports',
  box-cli:init   boxReportsFileFormat: 'txt',
  box-cli:init   boxDownloadsFolderPath: '/Users/ndu/Downloads/Box-Downloads',
  box-cli:init   outputJson: false,
  box-cli:init   enableProxy: false,
  box-cli:init   proxy: { url: null, username: null, password: null }
  box-cli:init } +1ms
  box-cli:init Using environment box_cli {
  box-cli:init   clientId: 'x1dq9czq0vlib00n4y2746apatefvoph',
  box-cli:init   clientSecret: 'clientSecret',
  box-cli:init   name: 'box_cli',
  box-cli:init   cacheTokens: true,
  box-cli:init   authMethod: 'oauth20'
  box-cli:init } +1ms
  box-cli:execute Starting execution command: files:upload argv: [ '/Users/ndu/Downloads/my.png', '-p', '159411462676', '--json', '-v' ] +0ms
  box-cli:execute Running framework error handler +1m
  box-cli:execute Handling re-thrown error in base command handler +20ms
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@box/cli/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:645:28)
    at ClientRequest.emit (node:events:526:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:758:9)
    at Object.onceWrapper (node:events:645:28)
    at TLSSocket.emit (node:events:538:35)
    at TLSSocket.Socket._onTimeout (node:net:501:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

### Versions Used
Box CLI:   @box/cli/3.0.0 darwin-x64 node-v16.14.2
Operating System: Mac OS 12.3 Monterey

**Comment by mwwoda** [comment]
Hi @fantasyado 

There are file upload issues when using a node version greater than v14. See https://github.com/box/boxcli/issues/238 Could you try downgrading your node version to v14 and try again?

Thanks,
Mateusz

**Comment by fantasyado** [comment]
@mwwoda  Thanks, downgrading the node version works.  Maybe it's better to specify the supported node version in the README or instructions.
