### ISSUE TITLE
Issue with uploading a file using cli.

### ISSUE THREAD

**Issue by bconroy1** [box/boxcli#308]
Hi,

I have a cron job that runs once a week which runs a psql query, outputs a file, gzips it, and uploads the file to box.

For some reason I am getting an empty file out there first, then when it tries to upload the "real" file it fails because
a file exists with that name.  

Has anyone seen that before, I know I don't have any other box uploads happening.

I am kinda doing a hacky work around that if I see that file existing I'll delete it before the real upload which may or may not even work because I don't know why the file is there in the first place.

Any help would be greatly appreciated.

thanks

bob

------
#!/bin/bash
today="$(date '+%Y-%m-%d')"

/home/bob/.nvm/versions/node/v12.13.0/bin/box configure:environments:add /home/bob/the-jobs/box_config/config.json

psql ..... (creates the csv file)

sleep 10

gzip $HOME/the-jobs/output/the-report-${today}.csv

sleep 10

/home/bob/.nvm/versions/node/v12.13.0/bin/box files:upload $HOME/the-jobs/output/the-report-${today}.csv.gz --parent-id 999999999

echo 'done'

---------

**Comment by arjankowski** [comment]
Hi @bconory1, 

Unfortunately I was unable to reproduce your issue.
Have you tried to upload this *.gz file from pure console without any script and cron job? Plese just run this command with

```
/home/bob/.nvm/versions/node/v12.13.0/bin/box files:upload $HOME/the-jobs/output/the-report-2022-04-20.csv.gz --parent-id 999999999
```

Is the final result is the same?
