### ISSUE TITLE
How to use box-cli on a linux server

### ISSUE THREAD

**Issue by fantasyado** [box/boxcli#320]
According to the document, the OAuth requires a browser to complete a login. But what if we are on a Linux server without a browser?  Is there any way to login the box-cli on it?

**Comment by lukaszsocha2** [comment]
Hi @fantasyado ,
for such case the best authentication method would be JWT Auth. Here is the link to the JWT Auth guide, which specifies how to set up your application properly: https://developer.box.com/guides/authentication/jwt/. And here is a link to the CLI documentation showing how to setup CLI to start using JWT auth - https://github.com/box/boxcli#cli-and-server-authentication-with-jwt. If you will have any further questions or problems let us know.
@lukaszsocha2

**Comment by fantasyado** [comment]
Thanks for reply.
