### ISSUE TITLE
Box Search: Limit param not supported

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#322]
- [ X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Box Search API supports a 'limit' parameter in the raw API See here https://box.dev/reference/get-search/

The Box CLI command for box search doesn't support that param and defaults to 100.

```
box search "Lorem" --scope=enterprise_content --csv --fields=id,name,owned_by --limit 200
Unexpected arguments: --limit, 200
See more help with --help
```

### Steps to Reproduce
Run command above

### Expected Behavior
Limit parameter available and honoured.

### Error Message, Including Stack Trace
See above

### Versions Used
Box CLI: 3.0.0
Operating System: mac Monterey

**Comment by lukaszsocha2** [comment]
Hi @jacquesvandermerwe ,
thanks for reporting this issue. I've already created pr, which will fix this.
Regards
