### ISSUE TITLE
Getting "This app can't run on your PC" for 3.0 installation file

### ISSUE THREAD

**Issue by adam801** [box/boxcli#325]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I have Box CLI 2.9 installed on my Windows machine. I'm trying to run the 3.0 installer, and get the message "This app can't run on your PC. To find a version for your PC, check with the software publisher."

![image](https://user-images.githubusercontent.com/52717894/166500812-b00401ca-97fa-482b-a1af-fc49d897ba41.png)

I went to the Compatibility tab of the file, clicked the Run compatibility troubleshooter, and it set the mode to be Windows 8. I then tried to run again, and still got the same error.

![image](https://user-images.githubusercontent.com/52717894/166501018-c7e876b0-c101-4049-99ab-7c6ac9336a13.png)

![image](https://user-images.githubusercontent.com/52717894/166501035-13deff24-8412-4c89-b9d7-a87c418d1b91.png)

My PC:
Latitude 7400
Processor: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz
Installed RAM: 32 GB
Windows 10 Pro
Version: 21H2
OS build: 19044.1645
Experience: Windows Feature Experience Pack 120.2212.4170.0

### Steps to Reproduce
1. Download exe from github: https://github.com/box/boxcli/releases/download/v3.0.0/box-v3.0.0-x64.exe
2. Run exe to install

### Expected Behavior
Expected it to install without errors.

### Error Message, Including Stack Trace
![image](https://user-images.githubusercontent.com/52717894/166501559-fed215aa-b997-4203-ab1f-be0e74e0dd5b.png)

### Screenshots
See above

### Versions Used
Box CLI: Currently 2.9
![image](https://user-images.githubusercontent.com/52717894/166501681-1000c16d-c6d9-40d1-a494-268f1b888ca1.png)

Operating System: 
Windows 10 Pro
Version: 21H2
OS build: 19044.1645
Experience: Windows Feature Experience Pack 120.2212.4170.0

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

Thanks.
Adam

**Comment by mwwoda** [comment]
Hi @adam801 

I tried installing v3.0.0 on my existing cli v2.9.0 installation and everything ran without problems. I am using a VM running Win10 Pro 64bit with version 21H2. You should not need to set any compatibility mode when installing CLI. It runs natively on Win10.

Can you provide your system type (os and cpu bit architecture)? You can find it in the System tab in the Control Panel. This problem often occurs when the installer architecture is not the same as your computer architecture. Also, try running the installer with administrator privileges, as this could solve your problem.

You can also try to install the 32-bit version or perform a clean install (delete the existing installation and then install the new one).

Thanks

**Comment by mwwoda** [comment]
Hi @adam801 

Is this still a problem? Did any of my tips help?

**Comment by mwwoda** [comment]
I'm glad it worked!
