### ISSUE TITLE
Windows 11 Compatibility?

### ISSUE THREAD

**Issue by robertbatchelor** [box/boxcli#344]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I recently moved to W11, and found I cant get the BOX CLI working.

I may be blind, but couldn't find any existing info for Box CLI on W11.

### Steps to Reproduce
Install either version of Box CLI on Windows 11

### Error Message, Including Stack Trace
`Error: The platform is windows 10 but the native module could not be found
    at checkPlatform (C:/Program Files/@boxcli/client/node_modules/node-ms-passport/index.js:59:19)
    at loadNativeModule (C:/Program Files/@boxcli/client/node_modules/node-ms-passport/index.js:71:16)
    at Object.<anonymous> (C:/Program Files/@boxcli/client/node_modules/node-ms-passport/index.js:29:25)
    at Object.<anonymous> (C:/Program Files/@boxcli/client/src/box-command.js:32:7)`

### Screenshots
![image](https://user-images.githubusercontent.com/103787842/174778382-4089544d-3870-4e46-9d94-c0d488de90c4.png)

### Versions Used
Box CLI:
![image](https://user-images.githubusercontent.com/103787842/174778139-bcb0cb07-2f9f-48cb-95f8-2cfb65209671.png)
Also tried the x86 version on a fresh install

Operating System:
![image](https://user-images.githubusercontent.com/103787842/174778245-1aa29775-f24a-4cab-8b28-b75e89dfbe98.png)

**Comment by robertbatchelor** [comment]
Well it looks like this might actually just be related to the latest release in this repo, v3.1.0

I formatted a fresh install of Windows 10 10.0 on a different system, and had the same issue with Box CLI v3.1.0.

Removing and re-installing v3.0.0 eliminated the above errors.

**Comment by mhagmajer** [comment]
Hello @robertbatchelor, thanks for reporting and including all these details! We are already tracking this internally as SDK-2316. We'll update you with more information as it comes. I'm glad that reverting back to v3.0.0 solved this problem for you!
