### ISSUE TITLE
Add progress bar to box users:transfer-content

### ISSUE THREAD

**Issue by jkhancock31** [box/boxcli#349]
When transferring data from one account to another using the command, box users:transfer-content, there is no progress bar indicating which account is being worked on and the overall percentage of completion.

Example use case: Transferring the data of hundreds or thousands of accounts to a Box holding account within the tenant. This process can take hours depending on the number of users and there is no way to check the progress. All you see is the command running with no information. The only way to gauge the progress of the move is by going into the Box account storing the data and checking it.

This would be a great quality of life improvement for this command.

**Comment by lukaszsocha2** [comment]
Hi @jkhancock31,
thanks for reaching us out. This is a nice idea for an enhancement. I'll add it to our backlog. (For internal tracking SDK-2362).
Best,
@lukaszsocha2

**Comment by mgrytsai** [comment]
Hi @jkhancock31 ,

Thanks for your suggestion. We did an investigation, and unfortunately the API doesn't provide a way to check the status of the transfer. Hence, we won't be able to add progress bar to the transfer-content command. Upload and download commands already have progress bar.

API reference - https://developer.box.com/reference/put-users-id-folders-0
