### ISSUE TITLE
box login error

### ISSUE THREAD

**Issue by hubentu** [box/boxcli#363]
Hi,

I try to follow the quick-start to login with CLI, but got the following error. Could you please help?

$ box login
If you are not using the quickstart guide to set up (https://developer.box.com/guides/tooling/cli/quick-start/) then go to the Box Developer console (https://cloud.app.box.com/developers/console) and:
1. Select an application with OAuth user authentication method. Create a new Custom App if needed.
2. Click on the Configuration tab and set the Redirect URI to: http://localhost:3000/callback. Click outside the input field.
3. Click on Save Changes.
? What is the OAuth Client ID of your application? c8xxxxxx
? What is the OAuth Client Secret of your application? pixxxxxxx
**_Cannot set property 'name' of undefined_**

Thanks,
Qiang

**Comment by arjankowski** [comment]
Hi @hubentu, thank for this issue.
We've already fix this in #364 and plan to release new CLI version with this fix soon.

Regards,
Artur
