### ISSUE TITLE
Folder items list returns duplicate results

### ISSUE THREAD

**Issue by zsofiaszabo** [box/boxcli#388]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The `box folders:items 0` command returns some folders multiple times. This has happened with multiple user accounts both with as-user and user tokens, and it continues to return the same folder multiple times if the command is submitted again.
This functionality does not occur when directly sending an endpoint request via Postman.

### Expected Behavior
Every item only returned once

### Screenshots
Example of folder being returned twice
<img width="572" alt="Screen Shot 2022-08-23 at 10 53 20" src="https://user-images.githubusercontent.com/54024964/186129973-e44c5350-a604-4ed8-a3db-fb4744fe41c9.png">

### Versions Used
Box CLI: 3.0.0 (also reproduced on version 3.3.2)
Operating System: macOS 12.4 Monterey

**Comment by arjankowski** [comment]
Hi @zsofiaszabo,

It turns out the Box API has an error getting data using the `usemarker` query parameter (which boxcli uses).
This has been reported to the appropriate team to take care of it.

I'm closing this problem because it's not because of boxcli.

Regards,
@arjankowski
