### ISSUE TITLE
Allow the box users:transfer-content and box users:delete to accept email addresses

### ISSUE THREAD

**Issue by jkhancock31** [box/boxcli#423]
### Is your feature request related to a problem? Please describe.
When transferring data or deleting accounts, the Box ID must always be used.

### Describe the solution you'd like
It would be a great enhancement to allow the email address of a Box account to be used in place of the Box ID. Box only allows one email address per account and when using SSO, this email address is always consistent and never duplicated in Box. This will also help to quickly troubleshoot which accounts are causing issues with transfers or deletions and eliminate the steps of having to look up users based on the ID's in the CLI or API and then look up the account in the Box web interface.

### Describe alternatives you've considered
There are no current alternatives.

### Additional context
<None.>

**Comment by arjankowski** [comment]
hi @jkhancock31,

Thanks for your feedback. Since this is not a direct boxcli change, but an API change, please send your suggestion on the page created for this purpose [here](https://pulse.box.com/forums/909778-help-shape-the-future-of-box?category_id=357814).
