### ISSUE TITLE
How do you get the direct download link?

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#426]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am trying to get the direct download URL using Box CLi
This is possible using Box Rest API but I did not see any options with the CLI.

### Steps to Reproduce
Rest API for shared links provides the download URL
https://developer.box.com/reference/get-files-id--get-shared-link/

### Expected Behavior
As a content manager I would like to be able to get direct download urls to embed them in my portal

### Versions Used
Box CLI: @box/cli/3.5.0 darwin-x64 node-v14.19.3
Operating System: macos 13

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/boxcli/search?type=Issues

**Comment by arjankowski** [comment]
Hi @Band-Aid ,

To get download url you just need to [call](https://github.com/box/boxcli/blob/main/docs/files.md#box-filesget-id):

```
$ box files:get ID
```

as `shared-link` is just a field of [File](https://developer.box.com/reference/resources/file/#param-shared_link)

Hope this help,
Artur

**Comment by Band-Aid** [comment]
Thanks! Though I am getting an error trying to create a shared link,
I was trying to create link but I get the following error. Am I doing something wrong here?

```
% box files:shared-links:create 123456 --access:open
Unexpected argument: --access:open
```

**Comment by arjankowski** [comment]
Please try that way:

```
 box files:shared-links:create 123456 --access open
```

as param values we should pass after a space or a `= `sign

**Comment by Band-Aid** [comment]
Ah, thanks for pointing that out... I must be tired. Your docs clearly state to use `=`. 

`--access=access `

Thanks again!
