### ISSUE TITLE
Request to add support for folder update collaborators

### ISSUE THREAD

**Issue by DonJuanAlejandro** [box/boxcli#435]
### Is your feature request related to a problem? Please describe.
With introduction of co-authoring, using the "hide collaborators" function at a folder level gives us control over which folders do NOT allow co-authoring.  We intend to programmatically and selectively disable collaborators through the CLI as it's more accessible to our teams than the API is directly.  

### Describe the solution you'd like
Per API docs, enable reading/updating the following two settings within folder get and update commands. 
can_non_owners_invite_collaborators
can_non_owners_invite
  referring to this:
  https://developer.box.com/reference/put-folders-id/

### Describe alternatives you've considered
2 options - manually tick the checkbox on each folder (eeeeks!) or write something more complex to allow novices to make direct API calls to make the change (less eeks!)

### Additional context
Really love the CLI tools!

**Comment by antusus** [comment]
Hi @DonJuanAlejandro ,

Thanks for submitting this Issue! I've added this to our roadmap and we will deliver that in the future.

@antusus
