### ISSUE TITLE
boxcli: Get a file embed URL

### ISSUE THREAD

**Issue by skchronicles** [box/boxcli#439]
# Get a file embed URL

- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
It is possible to currently get/generate a file embed URL with the box cli. I tried searching through your documentation, and I couldn't find any information. I know it is possible with the [python SDK](https://github.com/box/box-python-sdk/blob/main/docs/usage/files.md#get-an-embed-link). If this is not possible, would it be possible to add in a future release of the tool?  

![image](https://user-images.githubusercontent.com/18038345/206555870-fb6d90f3-f611-4081-be6a-2456853fde88.png)

Thank you for the help and maintaining this awesome tool,
@skchronicles

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/boxcli/search?type=Issues

**Comment by arjankowski** [comment]
Hi @skchronicles ,

Some of the file properties are not returned by default, when executing the `files:get` command. 
`expiring_embed_link` is just on of them. To obtain them, you must explicitly indicate them in the `fields` parameter when executing the command. Please read [this](https://developer.box.com/reference/get-files-id/#param-fields).

So to get the `embed_url` for a file you can exectue the following command:

```
box files: get <FILE_ID> --json --fields='expiring_embed_link'
```

Then the url will be placed in the `expiring_embed_link.url` property.

Hope this help!
Artur

**Comment by skchronicles** [comment]
Okay, that sounds good. Thank you for the help!
