### ISSUE TITLE
Implement command for fresh Authorization process when refresh token expires

### ISSUE THREAD

**Issue by rorycoconnor** [box/boxcli#448]
### Is your feature request related to a problem? Please describe.
While many Box customers are using the CLI daily or weekly, some only use it when there are pressing needs every few months or so. Due to this gap in usage, the refresh token stored with the CLI OAuth2.0 solution may expire. The process for generating new tokens is not straightforward, requiring the user to overwrite their working CLI Environment or creating a new one.

### Describe the solution you'd like
A command that will use an existing environment with the stored ClientID/Client Secret to automatically bring up the "Grant Access to Box" page in the user's browser. Something like **box configure:environments:refresh environment=[environment_name]**. 

### Describe alternatives you've considered
Another option is a prompt when the user receives the "Refresh Token Expired" error to begin the re-auth process.

### Additional context
Screenshot of the error a user receives:
![image](https://user-images.githubusercontent.com/31426874/211038538-1ab03bf2-4768-41b6-b1fe-5bff8c8547b9.png)

**Comment by antusus** [comment]
Hi @rorycoconnor ,

Thanks for submitting this Issue! I'll add this idea to our triage.

@antusus

**Comment by mgrytsai** [comment]
See PR #457. We'll release new CLI version in the next few weeks with this feature.

**Comment by mgrytsai** [comment]
@rorycoconnor Want to let you know that we released [Box CLI 3.8.0 version](https://github.com/box/boxcli/releases/tag/v3.8.0) which has now the feature you requested.
