### ISSUE TITLE
Can I restrict usage of Box CLI to only allow uploading to a single folder?

### ISSUE THREAD

**Issue by j-signorelli** [box/boxcli#479]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am interested in using Box CLI but only restricting access to allow uploads to a single folder on my Box drive in terminal on Linux. Is this possible? It seems that I can only allow entire write access or not.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/boxcli/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @j-signorelli,
to restrict permission to just one folder you can use `tokens:exchange` command with `--folder-id` flag, e.g:
`box tokens:exchange item_upload --folder-id=0`.
I will return a downscoped token to a specified folder. Please see documentation of this command: https://github.com/box/boxcli/blob/main/docs/tokens.md#box-tokensexchange-scope
Hope this helps,
@lukaszsocha2
