### ISSUE TITLE
Could not upload file

### ISSUE THREAD

**Issue by Mki-developer** [box/boxcli#500]
Question related to #231 
- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When executing the box folders:upload command, the only output is Could not upload file (the path to any of the files contained in the folder).
The behavior is that the upload of files contained in the folder fails at a low rate, but the upload of files in the middle of the folder seems to succeed.
Errors occur occasionally, sometimes twice in a row.

### Steps to Reproduce
Execute the box folders:upload command.

### Expected Behavior
Folders and files contained in the folders are uploaded to Box.

### Error Message, Including Stack Trace
Could not upload file (path to any of the files contained in the folder)

### Versions Used
Box CLI: 3.3.2
node.js:14.19.3
Operating System:Windows10

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/boxcli/search?type=Issues

**Comment by arjankowski** [comment]
Hi @Mki-developer ,

Thanks for submitting this Issue! 
I tried to reproduce this on my local machine: Win 10, @box/cli/3.3.2 win32-x64 node-v14.19.3, by uploading a folder with 300MB and the problem did not occur.

So I have a few questions that will allow us to further explore this issue:
1) Are you using boxcli with x64 arch or x86?
2) What authentication do you use, is it JWT, OAuth, CCG?
3) What is the size of the folder you are uploading?
4) Do the files whose upload causes an error have something in common, e.g. size, type?
5) Could you update to the current version 3.12.0 and check if the error still occurs by executing the same command but with the additional `-v` flag?

Regards,
@arjankowski

**Comment by Mki-developer** [comment]
Thank you for your question and investigation.

1. Are you using boxcli with x64 arch or x86?
→ I am using x64.

2. What authentication do you use, is it JWT, OAuth, CCG?
→ I use OAuth.

3. What is the size of the folder you are uploading?
4. Do the files whose upload causes an error have something in common, e.g. size, type?
→ The total number of files being uploaded is about 300, with a total size of about 250MB. The sizes of the files that showed the message "Could not upload file" were about 100KB and 1MB.

5. Could you update to the current version 3.12.0 and check if the error still occurs by executing the same command but with the additional -v flag?
→ I apologize, but I am currently unable to confirm this. Is confirmation necessary for your investigation?

**Comment by mwwoda** [comment]
Confirming whether the problem still exists in the latest version of the SDK would be very helpful, as so far we have not been able to reproduce the problem locally. You could also try to run the command with `--verbose` flag or using [Oclif debug](https://oclif.io/docs/debugging/) so we could get more information about the problem.
