### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by vaderj** [box/boxcli#512]
### I have checked that the SDK documentation doesn't solve my issue.

- [X] Yes I've checked them.

### I have checked that the API documentation doesn't solve my issue.

- [X] Yes I've checked them.

### I have checked that the Box Developer Forums doesn't solve my issue.

- [X] Yes I've checked them.

### I have searched Issues in this repo and my issue isn't already reported.

- [X] Yes I've checked them.

### Describe the bug

--no-overwrite is ignored

![image](https://github.com/box/boxcli/assets/5408195/f9fdc643-e1fc-4ef9-9498-69e85a7d7363)

### Expected behavior

--no-overwrite should NOT prompt me to overwrite an existing file

### Steps to reproduce

use --no-overwrite switch while downloading

### Authentication method used in your application

Developer Token

### App Access Level

App + Enterprise Access

### What is Box CLI Version and Node used?

3.12.0 win32-x64 node-v14.19.3

### What is your Operating  System Version?

WinServer 2019

**Comment by arjankowski** [comment]
Hi @vaderj, 
Thanks for reporting this issue! 
We've just fixed that, and soon we will release a new version of boxcli with this fix.

Regards,
Artur
