### ISSUE TITLE
Not able to rename folders in CLI (Command Line Interface)

### ISSUE THREAD

**Issue by fvigeant** [box/boxcli#52]
Hi 
I have open a ticket (1521837), stating that I cannot rename folders using the Box CLI application (e.g. box folders update 40517760245 --name blablabal --as-user 2752632349). The support team was able to recreate the problem and they asked me to an issue directly to you site.

The goal is to rename many folders for many users in our Enterprise Box. It is IMPORTANT and URGENT. What is the resolution path, timeline or any other options that we have?
Thanks

**Comment by allenmichael** [comment]
Marking as fixed with Pull Request #51
