### ISSUE TITLE
sign-requests:create doesn't work with bulk-file-path

### ISSUE THREAD

**Issue by kobay** [box/boxcli#529]
### I have checked that the SDK documentation doesn't solve my issue.

- [x] Yes I've checked them.

### I have checked that the API documentation doesn't solve my issue.

- [X] Yes I've checked them.

### I have checked that the Box Developer Forums doesn't solve my issue.

- [X] Yes I've checked them.

### I have searched Issues in this repo and my issue isn't already reported.

- [X] Yes I've checked them.

### Describe the bug

I would like to report an issue with the Box CLI.
When using the command `box sign-requests:create --bulk-file-path=data.csv`, the following error message is displayed:

```
Cannot convert undefined or null to object
```

### Expected behavior

sign-requests are created.

### Steps to reproduce

execute `box sign-requests:create --bulk-file-path=data.csv`

### Authentication method used in your application

Server Authentication (with JWT)

### App Access Level

App + Enterprise Access

### What is Box CLI Version and Node used?

@box/cli/3.12.2 darwin-arm64 node-v20.9.0

### What is your Operating  System Version?

macOS sonoma 14.5

**Comment by lukaszsocha2** [comment]
Hi @kobay,

Thank you for reaching out to us. Could you please provide a sample of the data.csv file? We only need the header line and one example line of data. Please ensure no sensitive information is included—feel free to use mock data instead.

Best regards,
@lukaszsocha2

**Comment by arjankowski** [comment]
Hi @kobay,

We have just released version `3.14.1` with a fix for the issue you reported 🚀
Thanks for your cooperation and for using our tool :) 

Regards
Artur

**Comment by kobay** [comment]
Thanks guys! I tested with `3.14.1`, and it's working!
