### ISSUE TITLE
Linux binary?

### ISSUE THREAD

**Issue by sid-kap** [box/boxcli#55]
Is there any chance that you guys might sometime provide a linux binary, in addition to the Windows and Mac binaries?

**Comment by allenmichael** [comment]
Hey Sid,

We've been considering how best to publish the Linux version of the CLI. We developed installers for Mac and Windows, and would like to look at adding to apt-get or something similar in the future potentially for Debian-based Linux, but we haven't ironed out solid plans quite yet.

With that said, you can actually generate a binary for Ubuntu right now from this repo. 

You'll need [.Net Core](https://www.microsoft.com/net/learn/get-started/linuxredhat) and Git installed first.

Run these commands next:
```sh
git clone https://github.com/box/boxcli
cd boxcli/BoxCLI
dotnet publish -c Release -r ubuntu.16.04-x64
./bin/Release/netcoreapp2.0/ubuntu.16.04-x64/publish/box
```
The `publish` folder under ./bin/Release/netcoreapp2.0/ubuntu.16.04-x64/ will contain all needed files to run the executable `box`. You can copy that folder wherever you'd like and add the folder path to `publish` to your environment variable PATH.

I'll leave this issue open until we make a decision on how to support Linux in the future in case others have similar questions and want to generate the binary on their own as well.

**Comment by sid-kap** [comment]
Would it be possible to send me the binary in the interim, before such a decision is made? I was unable to figure out how to build it myself.

**Comment by allenmichael** [comment]
Here's a link to download a .zip with the executable:
[https://cloud.box.com/s/p10oacdawh8pktgxut8uymrdxlmj9bfg](https://cloud.box.com/s/p10oacdawh8pktgxut8uymrdxlmj9bfg)

Once you download and unzip, you should have a folder named `publish`. From the directory containing the `publish` folder, you can run `./publish/box` to test that the executable runs. You can add the `box` command to your path by using `export` in your bash_rc file with the full path to the `publish` folder, or you can create a symlink:
`ln -s /path/to/publish /usr/local/bin/box` (don't copy this command directly, and instead, replace the /path/to/publish with the actual path to the publish folder on your system.)

**Comment by sid-kap** [comment]
Thanks!!

**Comment by MrMauricioLeite** [comment]
Thanks for providing the linux binary guys.
This is super helpful to sync with my servers and enabled us to step up our game on easily and securely integrating data

**Comment by joeyancheta** [comment]
Hi @allenmichael , I was wondering if there has been any plans for a debian-based Linux distro like CentOS?

**Comment by allenmichael** [comment]
@joeyancheta You can build for Debian and even CentOS specifically. See this list https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids

Clone the repo and change to the `BoxCLI` directory. Then use the following command to build the binary: `dotnet publish -c Release -r debian-x64`. You'll see a `bin` directory in the `BoxCLI` directory, and as you navigate down to the `publish` directory, you'll find the `box` binary and its dependencies.

**Comment by cgreene** [comment]
It looks like this got inadvertently closed by @sid-kap. 

Or at least, the plan from @allenmichael was:
> I'll leave this issue open until we make a decision on how to support Linux in the future in case others have similar questions and want to generate the binary on their own as well.

I'd love to see this distributed through some accessible channel too, so I'd love to see it get reopened.

**Comment by mattwiller** [comment]
@cgreene We're planning to add support for Linux in the next major version of the CLI, which is currently scheduled for release by the end of this year.

**Comment by jgoldhammer** [comment]
I think, this ticket can be closed with box-cli 2.0 release. Right, @mattwiller ?

**Comment by mattwiller** [comment]
@jgoldhammer Unfortunately, we're blocked on a couple of upstream issues in our build tools and haven't been able to release the Linux binaries yet.  I'll update this issue when we get them built and released!

**Comment by mattroyal** [comment]
@mattwiller We're really interested in this too (box-cli available for Linux) and thanks from us for your efforts in making this available!

**Comment by ttyS0** [comment]
FWIW, I'm using [pkg](https://www.npmjs.com/package/pkg) to build multi platform self contained binaries. So far it seems to work out well.

**Comment by zachzundel** [comment]
It looks like they've switched to a JavaScript implementation so the build instructions above are no longer usable. 

I figured out how to build the new one and published a package on the AUR called `boxcli-git`.

**Comment by kbehlers** [comment]
If you don't trust what someone else has compiled, here is what's working for me on Red Hat with the new node.js based CLI (aka box-cli-2.0), though I haven't tested it extensively.

1. Get node v10 (I'm using nvm and grabbing node v10.15.2)
2. Download and unzip the CLI source code (https://developer.box.com/docs/box-cli  -OR- https://github.com/box/boxcli/archive/v2.0.0.zip)
3. cd into the unzipped source code folder
4. in bash run `npx oclif multi` (no args if in the folder, see https://github.com/oclif/oclif )
5. Follow prompts, but don't override any files, say no to linting, typescript, and mocha (you could probably say yes to linting or mocha, I just haven't)
6. while still in the source folder, run `npm link` (this makes it so you can use `box` command from bash rather than `./bin/run` command from the source folder)
7. Follow the getting started instructions for the box cli (https://github.com/box/boxcli#getting-started) to setup your config file and start using commands

**Comment by ryanoff** [comment]
@kbehlers comments worked for me on Ubuntu 16.04

**Comment by ttyS0** [comment]
In case it helps, I rolled up what I do into a bash script : https://gist.github.com/ttyS0/345925677edfcd9194b7d2e9866eef1b

I use it to create self contained binaries as that's easier to distribute to folks internally.

**Comment by migueldiasbr** [comment]
> If you don't trust what someone else has compiled, here is what's working for me on Red Hat with the new node.js based CLI (aka box-cli-2.0), though I haven't tested it extensively.
> 
>     1. Get node v10 (I'm using nvm and grabbing node v10.15.2)
> 
>     2. Download and unzip the CLI source code (https://developer.box.com/docs/box-cli  -OR- https://github.com/box/boxcli/archive/v2.0.0.zip)
> 
>     3. cd into the unzipped source code folder
> 
>     4. in bash run `npx oclif multi` (no args if in the folder, see https://github.com/oclif/oclif )
> 
>     5. Follow prompts, but don't override any files, say no to linting, typescript, and mocha (you could probably say yes to linting or mocha, I just haven't)
> 
>     6. while still in the source folder, run `npm link` (this makes it so you can use `box` command from bash rather than `./bin/run` command from the source folder)
> 
>     7. Follow the getting started instructions for the box cli (https://github.com/box/boxcli#getting-started) to setup your config file and start using commands

Very nice instructions, but after some tries I am not able to identify the error below:

$ ./bin/run configure:environments:add ~/boxcli-2.3.0/MyConfigs.json
 ›   Error: command configure:environments:add not found

I'm running redhat 7.6, any advice?

**Comment by bjvt** [comment]
I gave up on box, and stuck with Dropbox.  Dropbox works fine on Ubuntu 
18.04 INTEGRATED with Nautilus.  Dropbox is expensive, and who uses 2 TB 
online?  but I have to stick with them.

**Comment by kbehlers** [comment]
> > If you don't trust what someone else has compiled, here is what's working for me on Red Hat with the new node.js based CLI (aka box-cli-2.0), though I haven't tested it extensively.
> > ```
> > 1. Get node v10 (I'm using nvm and grabbing node v10.15.2)
> > 
> > 2. Download and unzip the CLI source code (https://developer.box.com/docs/box-cli  -OR- https://github.com/box/boxcli/archive/v2.0.0.zip)
> > 
> > 3. cd into the unzipped source code folder
> > 
> > 4. in bash run `npx oclif multi` (no args if in the folder, see https://github.com/oclif/oclif )
> > 
> > 5. Follow prompts, but don't override any files, say no to linting, typescript, and mocha (you could probably say yes to linting or mocha, I just haven't)
> > 
> > 6. while still in the source folder, run `npm link` (this makes it so you can use `box` command from bash rather than `./bin/run` command from the source folder)
> > 
> > 7. Follow the getting started instructions for the box cli (https://github.com/box/boxcli#getting-started) to setup your config file and start using commands
> > ```
> 
> Very nice instructions, but after some tries I am not able to identify the error below:
> 
> $ ./bin/run configure:environments:add ~/boxcli-2.3.0/MyConfigs.json
> › Error: command configure:environments:add not found
> 
> I'm running redhat 7.6, any advice?

@migueldiasbr Do any commands show when you run `./bin/run` with no args or alternatively `./bin/run help`?

**Comment by migueldiasbr** [comment]
> > > If you don't trust what someone else has compiled, here is what's working for me on Red Hat with the new node.js based CLI (aka box-cli-2.0), though I haven't tested it extensively.
> > > ```
> > > 1. Get node v10 (I'm using nvm and grabbing node v10.15.2)
> > > 
> > > 2. Download and unzip the CLI source code (https://developer.box.com/docs/box-cli  -OR- https://github.com/box/boxcli/archive/v2.0.0.zip)
> > > 
> > > 3. cd into the unzipped source code folder
> > > 
> > > 4. in bash run `npx oclif multi` (no args if in the folder, see https://github.com/oclif/oclif )
> > > 
> > > 5. Follow prompts, but don't override any files, say no to linting, typescript, and mocha (you could probably say yes to linting or mocha, I just haven't)
> > > 
> > > 6. while still in the source folder, run `npm link` (this makes it so you can use `box` command from bash rather than `./bin/run` command from the source folder)
> > > 
> > > 7. Follow the getting started instructions for the box cli (https://github.com/box/boxcli#getting-started) to setup your config file and start using commands
> > > ```
> > 
> > 
> > Very nice instructions, but after some tries I am not able to identify the error below:
> > $ ./bin/run configure:environments:add ~/boxcli-2.3.0/MyConfigs.json
> > › Error: command configure:environments:add not found
> > I'm running redhat 7.6, any advice?
> 
> @migueldiasbr Do any commands show when you run `./bin/run` with no args or alternatively `./bin/run help`?

Hi @kbehlers , yes the command indeed shows the information bellow:

`
./run
Official command line interface for the Box API

VERSION
  @box/cli/2.0.0 linux-x64 node-v10.16.0

USAGE
  $ box [COMMAND]

COMMANDS
  autocomplete               Display autocomplete installation instructions
  collaboration-whitelist    List collaboration whitelist entries
  collaborations             Manage collaborations
  collections                List your collections
  comments                   Manage comments on files
  configure                  Configure the Box CLI
  device-pins                List all the device pins for your enterprise
  events                     Get events
  files                      Manage files
  folders                    Manage folders
  groups                     List all groups
  help                       Display help for the Box CLI
  legal-hold-policies        List legal hold policies
  metadata-cascade-policies  List the metadata cascade policies on a folder
  metadata-templates         Get all metadata templates in your Enterprise
  recent-items               List information about files accessed in the past 90 days up to a 1000 items
  request                    Manually specify a Box API request
  retention-policies         List all retention policies for your enterprise
  search                     Search for files and folders in your Enterprise
  shared-links               Manage shared links
  storage-policies           List storage policies
  tasks                      Manage tasks
  terms-of-service           List terms of services for your enterprise
  tokens                     Get a token. Returns the service account token by default
  trash                      List all items in trash
  users                      List all Box users
  watermarking               Apply a watermark on an item
  web-links                  Manage web links
  webhooks                   List all webhooks
`

**Comment by kbehlers** [comment]
@migueldiasbr Unfortunately if it is giving you that help prompt, I am not sure where to pinpoint it to. I copy/pasted the exact command you posted and it gives me the appropriate `Could not read environment config file...`.  Here are the only steps I can think of to try (and if you've done it a few times you may have tried all of them already)

- On reinstall, where I say `Follow prompts, but don't overwrite any files` try saying yes and overwrite the package.json and others.
- Run `npm-link`as I mention in step 6 so that you have a `box` command defined globally rather than using `./bin/run`
- If you have access to AWS or want to create a free AWS account, I have gotten it working on their free tier "Red Hat Enterprise Linux version 8 (HVM)". You might try the steps there and that would give you an environment I know I have it working in. If it does work there, that would at least let us narrow it to some factor in your other environment.

**Comment by ttyS0** [comment]
FWIW, these kind of issues is why I went the [npm pkg](https://www.npmjs.com/package/pkg) route. It eliminates all the distribution dependency mess.

**Comment by mattwiller** [comment]
@kbehlers If you already have Node.js installed on your machine, you should just be able to do `npm install --global @box/cli` to install the CLI — does that work for you?

**Comment by kbehlers** [comment]
@mattwiller Thank you! Yes it does! I definitely missed that as an option, thank you for stopping my dive any deeper down the 'oclif-as-a-intermediary' route.

**Comment by migueldiasbr** [comment]
> @kbehlers If you already have Node.js installed on your machine, you should just be able to do `npm install --global @box/cli` to install the CLI — does that work for you?

Hi  @mattwiller , thanks for this update! I did not know that... It worked, but idk why I can access "box" directly on terminal... I can see that it did created a link, but if I type box directly, it does not work. I'll check my path.

`npm install --global @box/cli
/usr/local/lib/nodejs/node-v10.16.0-linux-x64/bin/box -> /usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/@box/cli/bin/run
+ @box/cli@2.3.0`

**Comment by ianhorn** [comment]
> @kbehlers If you already have Node.js installed on your machine, you should just be able to do `npm install --global @box/cli` to install the CLI — does that work for you?

Yes.  This works for me.
