### ISSUE TITLE
commands for other box api functionality

### ISSUE THREAD

**Issue by whiggs** [box/boxcli#56]
Very useful tool.  Loving it.  It is ALMOST perfect.  I had to add the ALMOST in there because I couldn't help but notice that there are some box api features which the tool does not have commands for, like retention policies, legal holds, watermarks, among others.  I was wondering if there were any plans to incorporate all of the api features into the tool.  That would make this tool perfect.

**Comment by allenmichael** [comment]
We absolutely want to add complete parity with the API to the CLI! I obviously can't commit to a date quite yet, but our ultimate goal with the tool is to update it along with our SDKs to keep new API functionality accessible as soon as possible. Clearly, we're not there yet, but that's the goal we have in mind, granted that the CLI remains a tool that the Box community values.

To give some insight into the current iteration, we released a subset of API coverage with the initial version of the CLI to get the tool out and see what kind of interest there is within the Box community. 

Are there any other missing features or enhancements you'd like to see added to the CLI? We're scoping out work to start adding new features at some point in the near future, so we'd love to get any additional feedback you may have. 

I'm also so glad to hear you're loving the CLI! Our plans are to keep making it better over time.

**Comment by mattwiller** [comment]
@whiggs We're currently in the process of a major update of the CLI, and adding support for all currently-unsupported API endpoints will happen as a part of that effort.  We'll keep you updated when the new version is released!

**Comment by mattwiller** [comment]
@whiggs We recently released v2.0.0 of the CLI, which (to the best of my knowledge) includes support for all API functionality.  You can find the new installers over at https://github.com/box/boxcli/releases/tag/v2.0.0 — please give it a try and let us know if you run into any issues or missing API functionality!
