### ISSUE TITLE
403 error removing users from enterprise

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#58]
I can't remove users from the enterprise with a 403 error
box users uid --remove

grabbing the service token and running the same endpoint in cURL works fine.
curl -X PUT \
  https://api.box.com/2.0/users/1234567890 \
  -H 'authorization: Bearer xxxxxxxxxxxxxxxxxx' \
  -d '{"enteprise":null}'

**Comment by allenmichael** [comment]
The command for removing a user is not what you listed. Try using this:
box users delete <uid> 

You can add the --force or -f flag to delete the user even if the user owns content. I just checked with both a managed user and an app user and was able to delete both types of users. Make sure that your Box Application has the correct permissions for working with users in your Enterprise, not just App Users.

**Comment by Band-Aid** [comment]
Thanks. I'm trying to downgrade the user as a free user not delete.
Sorrry had a typo in my initial post. 
here's the command I am trying to execute
box users update uid --remove

`
$ box users update -h
Usage:  users update [arguments] [options]

Arguments:
  userId  User ID to Update

Options:
  --remove                         Remove the user from the enterprise, convert to free account
`

**Comment by allenmichael** [comment]
I was able to recreate the error with that command. It may be an issue with the underlying SDK and passing null objects to the JSON converter. I’ll investigate and update this issue when I’ve got a fix. Thanks for your report!

**Comment by Band-Aid** [comment]
not sure if this is the culprit looks like we are passing in a string "null" instead of null
https://github.com/box/boxcli/blob/10a1524fa80b7bccd369e6f91cc94ca5a40391ca/BoxCLI/Commands/UserSubCommands/UserSubCommandBase.cs#L171

https://developer.box.com/v2.0/reference#update-a-users-information
Set this to null to roll the user out of the enterprise and make them a free user

**Comment by allenmichael** [comment]
That's definitely one of the issues, however, the underlying .Net SDK powering the CLI typically ignores null fields when running the JSON converter, so the field won't be on the data, so it may be a bigger fix than just in the CLI. I will keep you updated.

**Comment by allenmichael** [comment]
Implemented a fix for the CLI in v1.1.1 (#59), still needs to be addressed in the .Net SDK. Closing.
