### ISSUE TITLE
Error when using user field of tracking_codes 

### ISSUE THREAD

**Issue by ericallen** [box/boxcli#62]
When using the the command
`box users list --fields id, name,status,tracking_codes` will return an error of `Error reading string. Unexpected token: StartObject. Path 'tracking_codes[0]', line 1, position 693.`.  Any variation of fields that include the tracking_codes will result with the error.  

Using boxcli 1.1.1 on macOS 10.13.2

**Comment by allenmichael** [comment]
Hi Eric,

There actually have been some issues with retrieving tracking_codes from the API itself. I currently don't have any users with tracking_codes assigned. Would you mind trying to use a tool like Postman or Curl to see if you can pull a user with a tracking_code directly from the API and what results you get? You can use `box tokens get` to return a token to use with either of those tools.

**Comment by allenmichael** [comment]
Just as a word of warning, please don't post the actual user details to this issue. I just want to confirm that you are able to retrieve tracking codes from the API. I'll take a look at the .Net SDK if you can successfully pull that info. You can use something like the following:

`curl https://api.box.com/2.0/users?fields=id,tracking_codes -H "Authorization: Bearer $token"`

**Comment by ericallen** [comment]
The API is returning the tracking codes for me.  With the command `curl "https://api.box.com/2.0/users/me?fields=id,tracking_codes" -H 'Authorization: Bearer ***** Hidden credentials *****'` I get a response like

`{
  "type": "user",
  "id": "****",
  "tracking_codes": [
    {
      "type": "tracking_code",
      "name": "ERP-ID",
      "value": "******"
    }
  ]
}`

**Comment by allenmichael** [comment]
Perfect! The issue then is with the underlying .Net SDK not having a correct model for tracking codes. I think right now it's just a `string[]`, so I think the JSON converter can't handle the more complex type getting returned. I'll work with that team and keep you updated. Thanks for the confirmation!

**Comment by allenmichael** [comment]
I opened a [pull request](https://github.com/box/box-windows-sdk-v2/pull/423) to the .Net SDK that you can watch. As soon as it's pulled in and a new SDK version is added to Nuget, I can update the CLI package.

**Comment by allenmichael** [comment]
This issue should be fixed with this current release v1.2.0 @ericallen
