### ISSUE TITLE
Feature Request: Add support for Collaboration Whitelist management for Governance customers

### ISSUE THREAD

**Issue by joshrael** [box/boxcli#68]
These functions were added to the .NET SDK recently.

**Comment by mattwiller** [comment]
@joshrael We're currently in the process of a major update of the CLI, and adding support for all currently-unsupported API endpoints will happen as a part of that effort.  We'll keep you updated when the new version is released!

**Comment by mattwiller** [comment]
@joshrael The new v2.0.0 release of the CLI includes support for managing the user's Collaboration Whitelist; you can download the latest installers at https://github.com/box/boxcli/releases/tag/v2.0.0 and get started by running `box collaboration-whitelist --help` for information about the new commands.  Please give it a try and let us know if you run into any issues!
