### ISSUE TITLE
Feature Request: Add Bulk Actions option to Groups endpoint

### ISSUE THREAD

**Issue by eirerocks** [box/boxcli#70]
Please consider introducing “Bulk Actions” for groups. The use case I came across was mass deletion of all groups in a test enterprise using the JSON file outputted from CLI

1) box groups list --save --file-format JSON

2) box groups delete **--bulk-file-path** ~/Documents/Box-Reports/groups-list-2018-03-01T15_46_04.json

**Comment by allenmichael** [comment]
This issue should be fixed with this current release v1.2.0 @eirerocks
