### ISSUE TITLE
--save --file-format not generating output file

### ISSUE THREAD

**Issue by rhsweeney** [box/boxcli#80]
Listing trash with as-user to be saved to a csv file doesn't appear to be supported.  Example:
`box trash list --as-user [UID] --save --file-format csv`

**Comment by mattwiller** [comment]
@rhsweeney We're currently working on a major update to the CLI and it looks like this issue is fixed in the new version.  We'll keep you updated when the new version is released to verify that this issue is resolved!

**Comment by mattwiller** [comment]
@rhsweeney The latest v2.0.0 release of the CLI should solve this issue!  You can find the latest installers at https://github.com/box/boxcli/releases/tag/v2.0.0 — please give the new version a try by running `box trash --as-user [UID] --csv --save` and let us know if you run into any other issues!
