### ISSUE TITLE
unable to export all users to csv. Converting IEnumerable types is not supported

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/boxcli#81]
Tried to export all users in the system to CSV file. Using
`box users list --file-format CSV --save`

This resulted in 
Converting IEnumerable types is not supported for a single field. If you want to do this, create your own ITypeConverter and register it in the TypeConverterFactory by calling AddConverter.
Error while saving file.

Then tried to limit the export to only the name and id field using 
box users list --file-format CSV --save -fields id,name

and it failed with exactly the same error. A report header was created that listed all the fields rather than just the fields specified.

**Comment by whiggs** [comment]
I am getting this error as well

**Comment by mattwiller** [comment]
@jacquesvandermerwe @whiggs This issue should now be fixed in v1.3.0 of the CLI — please try it out and let us know if you run into any other problems!
