### ISSUE TITLE
Unable to find environment

### ISSUE THREAD

**Issue by MicPYYC** [box/boxcli#84]
When trying to remove or set a specific environment, I get an error stating "Couldn't find this environment".  It does show when I list environments.  I am able to add / remove / set other environments with no issue.  I tried removing the application then adding it back but I assume the values are stored elsewhere and not in the main directory.

Version is 1.2.0

**Comment by allenmichael** [comment]
Under your `HOME` directory (depending on your OS) you'll have a `.box` folder. The path on a OSX for example is `~/.box/box_environments.json`. Inside you should see a `box_environments.json` file that is a JSON representation of your stored environments. Here's mine for example:

```json
{
    "default": "default",
    "environments": {
        "default": {
            "clientId": "k1kwpdocxc94ykkt26q251zwm6vw7o61",
            "enterpriseId": "954218",
            "boxConfigFilePath": "/Users/amsg/Downloads/954218_7wolz7vy_config.json",
            "hasInLinePrivateKey": true,
            "privateKeyPath": null,
            "name": "default",
            "defaultAsUserId": null,
            "useDefaultAsUser": false,
            "adminAsUserId": null,
            "tempAsUserId": null,
            "useTempAsUser": false,
            "userSessionExpiration": null,
            "userSessionEnabled": false
        }
    }
}
```

The environments are stored in an object called `environments` as key/value pairs, where the key is the name you gave the environment. You can edit this file to remove the environment you want or you can remove the file altogether and set up the CLI again.
