### ISSUE TITLE
Add support for creating and managing metadata-driven retention policies in the CLI

### ISSUE THREAD

**Issue by schwartzMS** [box/boxcli#85]
Add support for creating and managing metadata-driven retention policies in the CLI

https://developer.box.com/v2.0/docs/api-changelog#section-2018-04-11-metadata-driven-retention-policies

**Comment by mattwiller** [comment]
@schwartzMS We're currently in the process of a major update of the CLI, and adding support for all currently-unsupported API endpoints will happen as a part of that effort.  We'll keep you updated when the new version is released!

**Comment by sujaygarlanka** [comment]
@schwartzMS This should be addressed in this new version of the CLI. If this issue is not resolved, please feel free to re-open this issue.
