### ISSUE TITLE
Add support for metadata template deletion via the API to the CLI

### ISSUE THREAD

**Issue by schwartzMS** [box/boxcli#86]
Add support for metadata template deletion via the API to the CLI. This is now available via the Box Content API

https://developer.box.com/v2.0/reference#delete-metadata-template

**Comment by mattwiller** [comment]
@schwartzMS We're currently in the process of a major update of the CLI, and adding support for all currently-unsupported API endpoints will happen as a part of that effort.  We'll keep you updated when the new version is released!

**Comment by mattwiller** [comment]
@schwartzMS The latest v2.0.0 release of the CLI includes support for deleting metadata templates, under the `box metadata-templates:delete` command.  You can find the latest installers at https://github.com/box/boxcli/releases/tag/v2.0.0 — please try it out and let us know if you run into any issues!
