### ISSUE TITLE
BOX CLI command to extend External and Internal Collaborator Expiration

### ISSUE THREAD

**Issue by shyamramsetty** [box/boxcli#94]
Request to get the BOX CLI command to extend External and Internal Collaborator Expiration

**Comment by mattwiller** [comment]
Hi @shyamramsetty — we're working on a release of the Box CLI that includes full API coverage right now.  I'll make sure that this field is included in the next major release!

**Comment by shyamramsetty** [comment]
Hi Matt,

Thank you for the update.

As we are working on an emergency update plan for the VIP users in our organization, we are looking for the BOX CLI commands for our requirement.

Kindly let us know, when can we expect the update release from your team.

Regards,
[cid:image001.png@01D1331E.96FD6780]
Shyam Ramsetty
BOX Admin, IT, IDC - India
Baxter International Inc.
M +91- 904-345-6944
O +91- 804-620-9415 ; EXT - 2239415
shyam_ramsetty@baxter.com<mailto:shyam_ramsetty@baxter.com>

**Comment by shyamramsetty** [comment]
Hi Sam \ Alex \ Github Team,

As discussed earlier, I have already raised the new CLI feature request in “https://github.com/box/boxcli/issues” URL.

The issue log number which I got after raising the issues it #94 (https://github.com/box/boxcli/issues/94).

Kindly let us know, when can we expect the update release from your team, as we are working on an emergency update plan for the VIP users in our organization, we are looking for the BOX CLI commands for our requirement.

Also I have gone through the forum article on the Box Community page, saying that the feature need to be enabled even on Python to extend the expiration period for the external collaborators. Please find the below URL’s for your reference.


  1.  https://community.box.com/t5/Platform-and-Development-Forum/How-to-set-Collaborators-expiry-date-using-API-call/td-p/1750
  2.  https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#module-boxsdk.object.collaboration

Regards,
[cid:image001.png@01D1331E.96FD6780]
Shyam Ramsetty
BOX Admin, IT, IDC - India
Baxter International Inc.
M +91- 904-345-6944
O +91- 804-620-9415 ; EXT - 2239415
shyam_ramsetty@baxter.com<mailto:shyam_ramsetty@baxter.com>

From: Ramsetty, Shyam
Sent: Friday, June 29, 2018 1:40 PM
To: 'box/boxcli' <reply@reply.github.com>; box/boxcli <boxcli@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [box/boxcli] BOX CLI command to extend External and Internal Collaborator Expiration (#94)

Hi Matt,

Thank you for the update.

As we are working on an emergency update plan for the VIP users in our organization, we are looking for the BOX CLI commands for our requirement.

Kindly let us know, when can we expect the update release from your team.

Regards,
[cid:image001.png@01D1331E.96FD6780]
Shyam Ramsetty
BOX Admin, IT, IDC - India
Baxter International Inc.
M +91- 904-345-6944
O +91- 804-620-9415 ; EXT - 2239415
shyam_ramsetty@baxter.com<mailto:shyam_ramsetty@baxter.com>

**Comment by shyamramsetty** [comment]
+ Dave

[cid:image002.jpg@01D2AD2E.2AB8F130]

Saptarshi Mukherjee
Sr Mrg, IT Foundation Services (GDCi)
Baxter India Pvt.Ltd.
Cresent - 1, 10th Floor, Prestige Shantiniketan Campus
Bangalore - 560048
T +91.804.271.0604 / M +91.702.202.8193
saptarshi_mukherjee@baxter.com<mailto:saptarshi_mukherjee@baxter.com>

From: Ramsetty, Shyam
Sent: Thursday, July 12, 2018 5:21 PM
To: Samantha Skorcz <sskorcz@box.com>; Alex Butler <abutler@box.com>; box/boxcli <reply@reply.github.com>; box/boxcli <boxcli@noreply.github.com>; Box Customer Success <support+id1693171@box.zendesk.com>; Mention <mention@noreply.github.com>
Cc: Bhat, Gajanana <gajanana_bhat@baxter.com>; Mukherjee, Saptarshi <saptarshi_mukherjee@baxter.com>; Carlson, Eileen Theresa <eileen_carlson@baxter.com>; Rajendran, Shankar <shankar_rajendran@baxter.com>
Subject: RE: [box/boxcli] BOX CLI command to extend External and Internal Collaborator Expiration (#94)

Hi Sam \ Alex \ Github Team,

As discussed earlier, I have already raised the new CLI feature request in “https://github.com/box/boxcli/issues” URL.

The issue log number which I got after raising the issues it #94 (https://github.com/box/boxcli/issues/94).

Kindly let us know, when can we expect the update release from your team, as we are working on an emergency update plan for the VIP users in our organization, we are looking for the BOX CLI commands for our requirement.

Also I have gone through the forum article on the Box Community page, saying that the feature need to be enabled even on Python to extend the expiration period for the external collaborators. Please find the below URL’s for your reference.


  1.  https://community.box.com/t5/Platform-and-Development-Forum/How-to-set-Collaborators-expiry-date-using-API-call/td-p/1750
  2.  https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#module-boxsdk.object.collaboration

Regards,
[cid:image001.png@01D1331E.96FD6780]
Shyam Ramsetty
BOX Admin, IT, IDC - India
Baxter International Inc.
M +91- 904-345-6944
O +91- 804-620-9415 ; EXT - 2239415
shyam_ramsetty@baxter.com<mailto:shyam_ramsetty@baxter.com>

From: Ramsetty, Shyam
Sent: Friday, June 29, 2018 1:40 PM
To: 'box/boxcli' <reply@reply.github.com>; box/boxcli <boxcli@noreply.github.com<mailto:boxcli@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [box/boxcli] BOX CLI command to extend External and Internal Collaborator Expiration (#94)

Hi Matt,

Thank you for the update.

As we are working on an emergency update plan for the VIP users in our organization, we are looking for the BOX CLI commands for our requirement.

Kindly let us know, when can we expect the update release from your team.

Regards,
[cid:image001.png@01D1331E.96FD6780]
Shyam Ramsetty
BOX Admin, IT, IDC - India
Baxter International Inc.
M +91- 904-345-6944
O +91- 804-620-9415 ; EXT - 2239415
shyam_ramsetty@baxter.com<mailto:shyam_ramsetty@baxter.com>

**Comment by shyamramsetty** [comment]
Team,
Why do we need a Command Line Interface (CLI) feature update?  I thought we had this change working for 1 user and now need to make it work for many.
Are we making this more difficult than it has to be??
Thank you.
Dave Godfrey

[cid:image001.png@01D1331E.96FD6780]

David M. Godfrey
Director, IT
Baxter International Inc.
T 224.948.5734  /  M 224.475.8654
david_godfrey@baxter.com<mailto:david_godfrey@baxter.com>

From: Mukherjee, Saptarshi
Sent: Thursday, July 12, 2018 7:12 AM
To: Ramsetty, Shyam <shyam_ramsetty@baxter.com>; Samantha Skorcz <sskorcz@box.com>; Alex Butler <abutler@box.com>; box/boxcli <reply@reply.github.com>; box/boxcli <boxcli@noreply.github.com>; Box Customer Success <support+id1693171@box.zendesk.com>; Mention <mention@noreply.github.com>
Cc: Bhat, Gajanana <gajanana_bhat@baxter.com>; Carlson, Eileen Theresa <eileen_carlson@baxter.com>; Rajendran, Shankar <shankar_rajendran@baxter.com>; Godfrey, David M <david_godfrey@baxter.com>
Subject: RE: [box/boxcli] BOX CLI command to extend External and Internal Collaborator Expiration (#94)

+ Dave

[cid:image002.jpg@01D2AD2E.2AB8F130]

Saptarshi Mukherjee
Sr Mrg, IT Foundation Services (GDCi)
Baxter India Pvt.Ltd.
Cresent - 1, 10th Floor, Prestige Shantiniketan Campus
Bangalore - 560048
T +91.804.271.0604 / M +91.702.202.8193
saptarshi_mukherjee@baxter.com<mailto:saptarshi_mukherjee@baxter.com>

From: Ramsetty, Shyam
Sent: Thursday, July 12, 2018 5:21 PM
To: Samantha Skorcz <sskorcz@box.com<mailto:sskorcz@box.com>>; Alex Butler <abutler@box.com<mailto:abutler@box.com>>; box/boxcli <reply@reply.github.com>; box/boxcli <boxcli@noreply.github.com<mailto:boxcli@noreply.github.com>>; Box Customer Success <support+id1693171@box.zendesk.com<mailto:support+id1693171@box.zendesk.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Cc: Bhat, Gajanana <gajanana_bhat@baxter.com<mailto:gajanana_bhat@baxter.com>>; Mukherjee, Saptarshi <saptarshi_mukherjee@baxter.com<mailto:saptarshi_mukherjee@baxter.com>>; Carlson, Eileen Theresa <eileen_carlson@baxter.com<mailto:eileen_carlson@baxter.com>>; Rajendran, Shankar <shankar_rajendran@baxter.com<mailto:shankar_rajendran@baxter.com>>
Subject: RE: [box/boxcli] BOX CLI command to extend External and Internal Collaborator Expiration (#94)

Hi Sam \ Alex \ Github Team,

As discussed earlier, I have already raised the new CLI feature request in “https://github.com/box/boxcli/issues” URL.

The issue log number which I got after raising the issues it #94 (https://github.com/box/boxcli/issues/94).

Kindly let us know, when can we expect the update release from your team, as we are working on an emergency update plan for the VIP users in our organization, we are looking for the BOX CLI commands for our requirement.

Also I have gone through the forum article on the Box Community page, saying that the feature need to be enabled even on Python to extend the expiration period for the external collaborators. Please find the below URL’s for your reference.


  1.  https://community.box.com/t5/Platform-and-Development-Forum/How-to-set-Collaborators-expiry-date-using-API-call/td-p/1750
  2.  https://box-python-sdk.readthedocs.io/en/latest/boxsdk.object.html#module-boxsdk.object.collaboration

Regards,
[cid:image001.png@01D1331E.96FD6780]
Shyam Ramsetty
BOX Admin, IT, IDC - India
Baxter International Inc.
M +91- 904-345-6944
O +91- 804-620-9415 ; EXT - 2239415
shyam_ramsetty@baxter.com<mailto:shyam_ramsetty@baxter.com>

From: Ramsetty, Shyam
Sent: Friday, June 29, 2018 1:40 PM
To: 'box/boxcli' <reply@reply.github.com>; box/boxcli <boxcli@noreply.github.com<mailto:boxcli@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [box/boxcli] BOX CLI command to extend External and Internal Collaborator Expiration (#94)

Hi Matt,

Thank you for the update.

As we are working on an emergency update plan for the VIP users in our organization, we are looking for the BOX CLI commands for our requirement.

Kindly let us know, when can we expect the update release from your team.

Regards,
[cid:image001.png@01D1331E.96FD6780]
Shyam Ramsetty
BOX Admin, IT, IDC - India
Baxter International Inc.
M +91- 904-345-6944
O +91- 804-620-9415 ; EXT - 2239415
shyam_ramsetty@baxter.com<mailto:shyam_ramsetty@baxter.com>

**Comment by carycheng** [comment]
Hey @shyamramsetty, 

We are currently working on a new version of the cli slated to release in August. As far as the collaboration expiration we have a pull request out for that now at #95. However the person that manages the release of the cli is out until next week. When they get back in we'll chat about a potential release. 

Thank you for your patience
