### ISSUE TITLE
Enhancement: Tab auto-complete

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#97]
I would like to be able to auto-complete commands and options with TAB

**Comment by mattwiller** [comment]
@Band-Aid Thanks for writing in!  This is a feature we're considering in the next major update of the CLI — we'll keep you posted on progress.

**Comment by jgoldhammer** [comment]
Any progress here? 
I have thought about writing zsh autocomplete, but maybe you have something in place already?

Thanks
Jens

**Comment by mattwiller** [comment]
Hi @jgoldhammer — we don't have anything in place yet for the current version of the CLI, but we still plan to include this in the next major update!

**Comment by jgoldhammer** [comment]
Matt, so it means that is not worth it to do it. Any eta for new release? End of the year?

**Comment by mattwiller** [comment]
@jgoldhammer Correct, we're currently planning to release the next major update by end of year.

**Comment by mattwiller** [comment]
@Band-Aid @jgoldhammer We just released v2.0.0 of the CLI, which includes a brand-new `box autocomplete` command that provides instructions for adding tab auto-complete functionality for bash or zsh!  You can find the new installers over at https://github.com/box/boxcli/releases/tag/v2.0.0 — please give it a try and let us know if you run into any issues, or have any other feature requests.
