### ISSUE TITLE
ENHANCEMENT: Add option for id only when updating collaboration

### ISSUE THREAD

**Issue by jtrujillo3** [box/boxcli#98]
When adding a collaboration, you have the option to return only an ID from this command via --id-only.  When updating a collaboration, the collaboration ID changes but you are not able to save the new value from the command.  

The use case is for chaining a command to provision users and personal folders where the user is the only one collaborated in the folder.

Example of what chained command would look like:
FOLDER_ID="$(box folders create 0 "User's Folder" --id-only)" && USER_ID="$(box users create "User Name" "user@email.com" --id-only)" && COLLAB_ID="$(box collaborations add "$FOLDER_ID" folder --editor --user-id "$USER_ID" --id-only)" && NEWCOLLAB_ID="$(box collaborations update $COLLAB_ID --owner **--id-only**)" && "$(box collaborations delete $NEWCOLLAB_ID)"

**Comment by mattwiller** [comment]
@jtrujillo3 I'm unable to reproduce the situation you're describing — updating a collaboration via the Box API should **not** change the collaboration ID.  The same ID you used to update it is the ID you can use to delete it.  I just updated a collaboration via Postman, and its ID did not change.  Are you able to reproduce the issue you're seeing consistently?

**Comment by jtrujillo3** [comment]
i'm using the cli.  I do the following:
$userName = 'something' 
$userEmail = 'jtrujillo+testing@email.com'
$userFolder = 'Folder Name' 

$FOLDER_ID="$(box folders create 0 "$userFolder" --id-only)" 
$USER_ID="$(box users create "$userName" "$userEmail" --id-only)"  
$COLLAB_ID="$(box collaborations add "$FOLDER_ID" folder --editor --user-id "$USER_ID" --id-only)" 
write-host $collab_id 
## this returns 13598789126
box collaborations update $COLLAB_ID --owner 
box collaborations delete $COLLAB_ID -y 
## this returns: The API returned an error [NotFound | 1blb11ftmtwyg0f0] not_found - Not Found
box folders collaborations list $FOLDER_ID
## I see the collab ID in the response is 13598785403
box collaborations delete 13598785403 -y 
## collaboration get deleted

**Comment by mattwiller** [comment]
@jtrujillo3 Ahh, I see the issue.  If you're making the user the owner, then they no longer have a collaboration record — they own the item.  If you try this in Postman, you'll see that the API call to update the collaboration role to "owner" returns a 204 with no response body — there is literally no ID to return in that case.  It's unnecessary (and impossible) to delete the collaboration record after making the collaborator the owner.

**Comment by jtrujillo3** [comment]
@mattwiller reviewing and understand.  this type of update is expected to have the collab id change. I am able to do the previously mentioned use case using the CLI by manipulating the response of
 _box folders collaborations list $FOLDER_ID response_
and getting out the new collab id. I was just curious if there is a way to be able to get the new ID after update.  Appreciate you looking into this.
