### ISSUE TITLE
`box collaborations add --bulk-file-path` requiring both LoginID and LoginName

### ISSUE THREAD

**Issue by Band-Aid** [box/boxcli#99]
I had `AccessibleByLogin` in the csv file but get the following error.

```
14:14:31 ~/Desktop 
$ box collaborations add --bulk-file-path Book1.csv
Fields 'AccessibleById' do not exist in the CSV file.
```

Tried replacing `AccessibleByLogin` with `AccessibleById`
Now it wants `AccessibleByLogin`

```
14:14:56 ~/Desktop 
$ box collaborations add --bulk-file-path Book1.csv
Fields 'AccessibleByLogin' do not exist in the CSV file.
```

Adding both variables, the request went thru.
It should check if either exists or not instead of requiring both variables.

**Comment by mattwiller** [comment]
@Band-Aid Could you provide a sample of what the CSV file you're referencing looks like to reproduce this issue?

**Comment by Band-Aid** [comment]
Role | CanViewPath | ItemId | ItemType | AccessibleById | AccessibleByType | AccessibleByLogin
-- | -- | -- | -- | -- | -- | --
Editor |   | 1234578 | Folder | 23456789 | user | hello@hello.com

**Comment by allenmichael** [comment]
@mattwiller is right. The CSV header is required, but you simply leave the value empty and you can then use either field. Values in both fields is not required.
